package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * AnatomicalSystem
 *
 * An anatomical system is a group of anatomical structures that work together to perform a certain task. Anatomical systems, such as organ systems, are one organizing principle of anatomy, and can includes circulatory, digestive, endocrine, integumentary, immune, lymphatic, muscular, nervous, reproductive, respiratory, skeletal, urinary, vestibular, and other systems.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class AnatomicalSystem extends MedicalEntity {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/AnatomicalSystem";

  /**
   * If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
   */
  public String associatedPathophysiology;

  /**
   * Specifying something physically contained by something else. Typically used here for the underlying anatomical structures, such as organs, that comprise the anatomical system.
   */
  public AnatomicalStructure comprisedOf;

  /**
   * Specifying something physically contained by something else. Typically used here for the underlying anatomical structures, such as organs, that comprise the anatomical system.
   */
  public AnatomicalSystem comprisedOfAnatomicalSystem;

  /**
   * A medical condition associated with this anatomy.
   */
  public MedicalCondition relatedCondition;

  /**
   * Related anatomical structure(s) that are not part of the system but relate or connect to it, such as vascular bundles associated with an organ system.
   */
  public AnatomicalStructure relatedStructure;

  /**
   * A medical therapy related to this anatomy.
   */
  public MedicalTherapy relatedTherapy;
}

