package uk.co.polycode.schemaorg.org.schema;

import java.lang.Boolean;
import java.lang.String;
import java.math.BigInteger;

/**
 * Book
 *
 * A book.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Book extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Book";

  /**
   * The edition of the book.
   */
  public String bookEdition;

  /**
   * The format of the book.
   */
  public BookFormatType bookFormat;

  /**
   * The illustrator of the book.
   */
  public Person illustrator;

  /**
   * The ISBN of the book.
   */
  public String isbn;

  /**
   * Indicates whether the book is an abridged edition.
   */
  public Boolean abridged;

  /**
   * The number of pages in the book.
   */
  public BigInteger numberOfPages;
}

