package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * BusinessEntityType
 *
 * A business entity type is a conceptual entity representing the legal form, the size, the main line of business, the position in the value chain, or any combination thereof, of an organization or business person.<br/><br/>
 *
 * Commonly used values:<br/><br/>
 *
 * <ul>
 * <li>http://purl.org/goodrelations/v1#Business</li>
 * <li>http://purl.org/goodrelations/v1#Enduser</li>
 * <li>http://purl.org/goodrelations/v1#PublicInstitution</li>
 * <li>http://purl.org/goodrelations/v1#Reseller</li>
 * </ul>
 *
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BusinessEntityType extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/BusinessEntityType";
}

