package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * ContactPoint
 *
 * A contact point&#x2014;for example, a Customer Complaints department.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class ContactPoint extends StructuredValue {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/ContactPoint";

  /**
   * The geographic area where a service or offered item is provided.
   */
  public AdministrativeArea areaServed;

  /**
   * The geographic area where a service or offered item is provided.
   */
  public GeoShape areaServedGeoShape;

  /**
   * The geographic area where a service or offered item is provided.
   */
  public Place areaServedPlace;

  /**
   * A language someone may use with or at the item, service or place. Please use one of the language codes from the <a href="http://tools.ietf.org/html/bcp47">IETF BCP 47 standard</a>. See also <a class="localLink" href="https://schema.org/inLanguage">inLanguage</a>
   */
  public Language availableLanguage;

  /**
   * An option available on this contact point (e.g. a toll-free number or support for hearing-impaired callers).
   */
  public ContactPointOption contactOption;

  /**
   * A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.
   */
  public String contactType;

  /**
   * Email address.
   */
  public String email;

  /**
   * The fax number.
   */
  public String faxNumber;

  /**
   * The hours during which this service or contact is available.
   */
  public OpeningHoursSpecification hoursAvailable;

  /**
   * The product or service this support contact point is related to (such as product support for a particular product line). This can be a specific product or product line (e.g. "iPhone") or a general category of products or services (e.g. "smartphones").
   */
  public Product productSupported;

  /**
   * The telephone number.
   */
  public String telephone;
}

