package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigInteger;
import java.time.ZonedDateTime;

/**
 * CreativeWorkSeason
 *
 * A media season e.g. tv, radio, video game etc.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class CreativeWorkSeason extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/CreativeWorkSeason";

  /**
   * An actor, e.g. in tv, radio, movie, video games etc., or in an event. Actors can be associated with individual items or with a series, episode, clip.
   */
  public Person actor;

  /**
   * A director of e.g. tv, radio, movie, video gaming etc. content, or of an event. Directors can be associated with individual items or with a series, episode, clip.
   */
  public Person director;

  /**
   * An episode of a tv, radio or game media within a series or season.
   */
  public Episode episode;

  /**
   * The series to which this episode or season belongs.
   */
  public CreativeWorkSeries partOfSeries;

  /**
   * The production company or studio responsible for the item e.g. series, video game, episode etc.
   */
  public Organization productionCompany;

  /**
   * Position of the season within an ordered group of seasons.
   */
  public BigInteger seasonNumber;

  /**
   * The trailer of a movie or tv/radio series, season, episode, etc.
   */
  public VideoObject trailer;

  /**
   * The end date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime endDate;

  /**
   * The end date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime endDateZonedDateTime;

  /**
   * The number of episodes in this season or series.
   */
  public BigInteger numberOfEpisodes;

  /**
   * The start date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime startDate;

  /**
   * The start date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime startDateZonedDateTime;
}

