package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.time.ZonedDateTime;

/**
 * DataFeedItem
 *
 * A single item within a larger data feed.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DataFeedItem extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/DataFeedItem";

  /**
   * An entity represented by an entry in a list or data feed (e.g. an 'artist' in a list of 'artists')’.
   */
  public Thing item;

  /**
   * The date on which the CreativeWork was created or the item was added to a DataFeed.
   */
  public ZonedDateTime dateCreated;

  /**
   * The date on which the CreativeWork was created or the item was added to a DataFeed.
   */
  public ZonedDateTime dateCreatedZonedDateTime;

  /**
   * The datetime the item was removed from the DataFeed.
   */
  public ZonedDateTime dateDeleted;

  /**
   * The datetime the item was removed from the DataFeed.
   */
  public ZonedDateTime dateDeletedZonedDateTime;

  /**
   * The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
   */
  public ZonedDateTime dateModified;

  /**
   * The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
   */
  public ZonedDateTime dateModifiedZonedDateTime;
}

