package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * DefinedTermSet
 *
 * A set of defined terms for example a set of categories or a classification scheme, a glossary, dictionary or enumeration.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DefinedTermSet extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/DefinedTermSet";

  /**
   * A Defined Term contained in this term set.
   */
  public DefinedTerm hasDefinedTerm;
}

