package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigInteger;

/**
 * Episode
 *
 * A media episode (e.g. TV, radio, video game) which can be part of a series or season.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Episode extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Episode";

  /**
   * An actor, e.g. in tv, radio, movie, video games etc., or in an event. Actors can be associated with individual items or with a series, episode, clip.
   */
  public Person actor;

  /**
   * A director of e.g. tv, radio, movie, video gaming etc. content, or of an event. Directors can be associated with individual items or with a series, episode, clip.
   */
  public Person director;

  /**
   * The duration of the item (movie, audio recording, event, etc.) in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>.
   */
  public Duration duration;

  /**
   * Position of the episode within an ordered group of episodes.
   */
  public BigInteger episodeNumber;

  /**
   * The composer of the soundtrack.
   */
  public Person musicBy;

  /**
   * The composer of the soundtrack.
   */
  public MusicGroup musicByMusicGroup;

  /**
   * The season to which this episode belongs.
   */
  public CreativeWorkSeason partOfSeason;

  /**
   * The series to which this episode or season belongs.
   */
  public CreativeWorkSeries partOfSeries;

  /**
   * The production company or studio responsible for the item e.g. series, video game, episode etc.
   */
  public Organization productionCompany;

  /**
   * The trailer of a movie or tv/radio series, season, episode, etc.
   */
  public VideoObject trailer;
}

