package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * Grant
 *
 * A grant, typically financial or otherwise quantifiable, of resources. Typically a <a class="localLink" href="https://schema.org/funder">funder</a> sponsors some <a class="localLink" href="https://schema.org/MonetaryAmount">MonetaryAmount</a> to an <a class="localLink" href="https://schema.org/Organization">Organization</a> or <a class="localLink" href="https://schema.org/Person">Person</a>,
 *     sometimes not necessarily via a dedicated or long-lived <a class="localLink" href="https://schema.org/Project">Project</a>, resulting in one or more outputs, or <a class="localLink" href="https://schema.org/fundedItem">fundedItem</a>s. For financial sponsorship, indicate the <a class="localLink" href="https://schema.org/funder">funder</a> of a <a class="localLink" href="https://schema.org/MonetaryGrant">MonetaryGrant</a>. For non-financial support, indicate <a class="localLink" href="https://schema.org/sponsor">sponsor</a> of <a class="localLink" href="https://schema.org/Grant">Grant</a>s of resources (e.g. office space).<br/><br/>
 *
 * Grants support  activities directed towards some agreed collective goals, often but not always organized as <a class="localLink" href="https://schema.org/Project">Project</a>s. Long-lived projects are sometimes sponsored by a variety of grants over time, but it is also common for a project to be associated with a single grant.<br/><br/>
 *
 * The amount of a <a class="localLink" href="https://schema.org/Grant">Grant</a> is represented using <a class="localLink" href="https://schema.org/amount">amount</a> as a <a class="localLink" href="https://schema.org/MonetaryAmount">MonetaryAmount</a>.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Grant extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/Grant";

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Person fundedItem;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Product fundedItemProduct;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Organization fundedItemOrganization;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public CreativeWork fundedItemCreativeWork;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public MedicalEntity fundedItemMedicalEntity;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Event fundedItemEvent;

  /**
   * Indicates something directly or indirectly funded or sponsored through a <a class="localLink" href="https://schema.org/Grant">Grant</a>. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public BioChemEntity fundedItemBioChemEntity;

  /**
   * A person or organization that supports (sponsors) something through some kind of financial contribution.
   */
  public Person funder;

  /**
   * A person or organization that supports (sponsors) something through some kind of financial contribution.
   */
  public Organization funderOrganization;

  /**
   * A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.
   */
  public Person sponsor;

  /**
   * A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.
   */
  public Organization sponsorOrganization;
}

