package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigInteger;

/**
 * ListItem
 *
 * An list item, e.g. a step in a checklist or how-to description.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class ListItem extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/ListItem";

  /**
   * An entity represented by an entry in a list or data feed (e.g. an 'artist' in a list of 'artists')’.
   */
  public Thing item;

  /**
   * A link to the ListItem that follows the current one.
   */
  public ListItem nextItem;

  /**
   * The position of an item in a series or sequence of items.
   */
  public BigInteger position;

  /**
   * A link to the ListItem that preceeds the current one.
   */
  public ListItem previousItem;
}

