package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * MedicalConditionStage
 *
 * A stage of a medical condition, such as 'Stage IIIa'.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalConditionStage extends MedicalIntangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalConditionStage";

  /**
   * The substage, e.g. 'a' for Stage IIIa.
   */
  public String subStageSuffix;

  /**
   * The stage represented as a number, e.g. 3.
   */
  public BigDecimal stageAsNumber;
}

