package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.time.ZonedDateTime;

/**
 * MedicalGuideline
 *
 * Any recommendation made by a standard society (e.g. ACC/AHA) or consensus statement that denotes how to diagnose and treat a particular condition. Note: this type should be used to tag the actual guideline recommendation; if the guideline recommendation occurs in a larger scholarly article, use MedicalScholarlyArticle to tag the overall article, not this type. Note also: the organization making the recommendation should be captured in the recognizingAuthority base property of MedicalEntity.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalGuideline extends MedicalEntity {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalGuideline";

  /**
   * Strength of evidence of the data used to formulate the guideline (enumerated).
   */
  public MedicalEvidenceLevel evidenceLevel;

  /**
   * Source of the data used to formulate the guidance, e.g. RCT, consensus opinion, etc.
   */
  public String evidenceOrigin;

  /**
   * The medical conditions, treatments, etc. that are the subject of the guideline.
   */
  public MedicalEntity guidelineSubject;

  /**
   * Date on which this guideline's recommendation was made.
   */
  public ZonedDateTime guidelineDate;
}

