package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * MenuSection
 *
 * A sub-grouping of food or drink items in a menu. E.g. courses (such as 'Dinner', 'Breakfast', etc.), specific type of dishes (such as 'Meat', 'Vegan', 'Drinks', etc.), or some other classification made by the menu provider.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MenuSection extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/MenuSection";

  /**
   * A food or drink item contained in a menu or menu section.
   */
  public MenuItem hasMenuItem;

  /**
   * A subgrouping of the menu (by dishes, course, serving time period, etc.).
   */
  public MenuSection hasMenuSection;
}

