package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * MusicAlbum
 *
 * A collection of music tracks.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MusicAlbum extends MusicPlaylist {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/MusicAlbum";

  /**
   * Classification of the album by it's type of content: soundtrack, live album, studio album, etc.
   */
  public MusicAlbumProductionType albumProductionType;

  /**
   * A release of this album.
   */
  public MusicRelease albumRelease;

  /**
   * The kind of release which this album is: single, EP or album.
   */
  public MusicAlbumReleaseType albumReleaseType;

  /**
   * The artist that performed this album or recording.
   */
  public Person byArtist;

  /**
   * The artist that performed this album or recording.
   */
  public MusicGroup byArtistMusicGroup;
}

