package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * MusicRelease
 *
 * A MusicRelease is a specific release of a music album.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MusicRelease extends MusicPlaylist {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/MusicRelease";

  /**
   * The catalog number for the release.
   */
  public String catalogNumber;

  /**
   * The group the release is credited to if different than the byArtist. For example, Red and Blue is credited to "Stefani Germanotta Band", but by Lady Gaga.
   */
  public Person creditedTo;

  /**
   * The group the release is credited to if different than the byArtist. For example, Red and Blue is credited to "Stefani Germanotta Band", but by Lady Gaga.
   */
  public Organization creditedToOrganization;

  /**
   * The duration of the item (movie, audio recording, event, etc.) in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>.
   */
  public Duration duration;

  /**
   * Format of this release (the type of recording media used, ie. compact disc, digital media, LP, etc.).
   */
  public MusicReleaseFormatType musicReleaseFormat;

  /**
   * The label that issued the release.
   */
  public Organization recordLabel;

  /**
   * The album this is a release of.
   */
  public MusicAlbum releaseOf;
}

