package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * NewsArticle
 *
 * A NewsArticle is an article whose content reports news, or provides background context and supporting materials for understanding the news.<br/><br/>
 *
 * A more detailed overview of <a href="/docs/news.html">schema.org News markup</a> is also available.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class NewsArticle extends Article {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/NewsArticle";

  /**
   * A <a href="https://en.wikipedia.org/wiki/Dateline">dateline</a> is a brief piece of text included in news articles that describes where and when the story was written or filed though the date is often omitted. Sometimes only a placename is provided.<br/><br/>
   *
   * Structured representations of dateline-related information can also be expressed more explicitly using <a class="localLink" href="https://schema.org/locationCreated">locationCreated</a> (which represents where a work was created e.g. where a news report was written).  For location depicted or described in the content, use <a class="localLink" href="https://schema.org/contentLocation">contentLocation</a>.<br/><br/>
   *
   * Dateline summaries are oriented more towards human readers than towards automated processing, and can vary substantially. Some examples: "BEIRUT, Lebanon, June 2.", "Paris, France", "December 19, 2017 11:43AM Reporting from Washington", "Beijing/Moscow", "QUEZON CITY, Philippines".
   */
  public String dateline;

  /**
   * The number of the column in which the NewsArticle appears in the print edition.
   */
  public String printColumn;

  /**
   * The edition of the print product in which the NewsArticle appears.
   */
  public String printEdition;

  /**
   * If this NewsArticle appears in print, this field indicates the name of the page on which the article is found. Please note that this field is intended for the exact page name (e.g. A5, B18).
   */
  public String printPage;

  /**
   * If this NewsArticle appears in print, this field indicates the print section in which the article appeared.
   */
  public String printSection;
}

