package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * OccupationalExperienceRequirements
 *
 * Indicates employment-related experience requirements, e.g. <a class="localLink" href="https://schema.org/monthsOfExperience">monthsOfExperience</a>.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class OccupationalExperienceRequirements extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/OccupationalExperienceRequirements";

  /**
   * Indicates the minimal number of months of experience required for a position.
   */
  public BigDecimal monthsOfExperience;
}

