package uk.co.polycode.schemaorg.org.schema;

import java.lang.Boolean;
import java.lang.String;

/**
 * OfferShippingDetails
 *
 * OfferShippingDetails represents information about shipping destinations.<br/><br/>
 *
 * Multiple of these entities can be used to represent different shipping rates for different destinations:<br/><br/>
 *
 * One entity for Alaska/Hawaii. A different one for continental US.A different one for all France.<br/><br/>
 *
 * Multiple of these entities can be used to represent different shipping costs and delivery times.<br/><br/>
 *
 * Two entities that are identical but differ in rate and time:<br/><br/>
 *
 * e.g. Cheaper and slower: DOLLAR5 in 5-7days
 * or Fast and expensive: DOLLAR15 in 1-2 days.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class OfferShippingDetails extends StructuredValue {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/OfferShippingDetails";

  /**
   * The total delay between the receipt of the order and the goods reaching the final customer.
   */
  public ShippingDeliveryTime deliveryTime;

  /**
   * indicates (possibly multiple) shipping destinations. These can be defined in several ways e.g. postalCode ranges.
   */
  public DefinedRegion shippingDestination;

  /**
   * Label to match an <a class="localLink" href="https://schema.org/OfferShippingDetails">OfferShippingDetails</a> with a <a class="localLink" href="https://schema.org/ShippingRateSettings">ShippingRateSettings</a> (within the context of a <a class="localLink" href="https://schema.org/shippingSettingsLink">shippingSettingsLink</a> cross-reference).
   */
  public String shippingLabel;

  /**
   * The shipping rate is the cost of shipping to the specified destination. Typically, the maxValue and currency values (of the <a class="localLink" href="https://schema.org/MonetaryAmount">MonetaryAmount</a>) are most appropriate.
   */
  public MonetaryAmount shippingRate;

  /**
   * Link to a page containing <a class="localLink" href="https://schema.org/ShippingRateSettings">ShippingRateSettings</a> and <a class="localLink" href="https://schema.org/DeliveryTimeSettings">DeliveryTimeSettings</a> details.
   */
  public String shippingSettingsLink;

  /**
   * Label to match an <a class="localLink" href="https://schema.org/OfferShippingDetails">OfferShippingDetails</a> with a <a class="localLink" href="https://schema.org/DeliveryTimeSettings">DeliveryTimeSettings</a> (within the context of a <a class="localLink" href="https://schema.org/shippingSettingsLink">shippingSettingsLink</a> cross-reference).
   */
  public String transitTimeLabel;

  /**
   * Indicates when shipping to a particular <a class="localLink" href="https://schema.org/shippingDestination">shippingDestination</a> is not available.
   */
  public Boolean doesNotShip;
}

