package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.time.ZonedDateTime;

/**
 * OwnershipInfo
 *
 * A structured value providing information about when a certain organization or person owned a certain product.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class OwnershipInfo extends StructuredValue {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/OwnershipInfo";

  /**
   * The organization or person from which the product was acquired.
   */
  public Person acquiredFrom;

  /**
   * The organization or person from which the product was acquired.
   */
  public Organization acquiredFromOrganization;

  /**
   * The product that this structured value is referring to.
   */
  public Product typeOfGood;

  /**
   * The product that this structured value is referring to.
   */
  public Service typeOfGoodService;

  /**
   * The date and time of obtaining the product.
   */
  public ZonedDateTime ownedFrom;

  /**
   * The date and time of giving up ownership on the product.
   */
  public ZonedDateTime ownedThrough;
}

