package uk.co.polycode.schemaorg.org.schema;

import java.lang.Boolean;
import java.lang.String;
import java.time.ZonedDateTime;

/**
 * Product
 *
 * Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; a haircut; or an episode of a TV show streamed online.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Product extends Thing {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Product";

  /**
   * A property-value pair representing an additional characteristics of the entitity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.<br/><br/>
   *
   * Note: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.
   */
  public PropertyValue additionalProperty;

  /**
   * The overall rating, based on a collection of reviews or ratings, of the item.
   */
  public AggregateRating aggregateRating;

  /**
   * An intended audience, i.e. a group for whom something was created.
   */
  public Audience audience;

  /**
   * An award won by or for this item.
   */
  public String award;

  /**
   * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
   */
  public Organization brand;

  /**
   * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
   */
  public Brand brandBrand;

  /**
   * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
   */
  public Thing category;

  /**
   * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
   */
  public PhysicalActivityCategory categoryPhysicalActivityCategory;

  /**
   * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
   */
  public CategoryCode categoryCategoryCode;

  /**
   * The color of the product.
   */
  public String color;

  /**
   * The place where the product was assembled.
   */
  public String countryOfAssembly;

  /**
   * The place where the item (typically <a class="localLink" href="https://schema.org/Product">Product</a>) was last processed and tested before importation.
   */
  public String countryOfLastProcessing;

  /**
   * The country of origin of something, including products as well as creative  works such as movie and TV content.<br/><br/>
   *
   * In the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other kinds of <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a> it is difficult to provide fully general guidance, and properties such as <a class="localLink" href="https://schema.org/contentLocation">contentLocation</a> and <a class="localLink" href="https://schema.org/locationCreated">locationCreated</a> may be more applicable.<br/><br/>
   *
   * In the case of products, the country of origin of the product. The exact interpretation of this may vary by context and product type, and cannot be fully enumerated here.
   */
  public Country countryOfOrigin;

  /**
   * The depth of the item.
   */
  public Distance depth;

  /**
   * The depth of the item.
   */
  public QuantitativeValue depthQuantitativeValue;

  /**
   * A <a class="localLink" href="https://schema.org/Grant">Grant</a> that directly or indirectly provide funding or sponsorship for this item. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Grant funding;

  /**
   * A Global Trade Item Number (<a href="https://www.gs1.org/standards/id-keys/gtin">GTIN</a>). GTINs identify trade items, including products and services, using numeric identification codes. The <a class="localLink" href="https://schema.org/gtin">gtin</a> property generalizes the earlier <a class="localLink" href="https://schema.org/gtin8">gtin8</a>, <a class="localLink" href="https://schema.org/gtin12">gtin12</a>, <a class="localLink" href="https://schema.org/gtin13">gtin13</a>, and <a class="localLink" href="https://schema.org/gtin14">gtin14</a> properties. The GS1 <a href="https://www.gs1.org/standards/Digital-Link/">digital link specifications</a> express GTINs as URLs. A correct <a class="localLink" href="https://schema.org/gtin">gtin</a> value should be a valid GTIN, which means that it should be an all-numeric string of either 8, 12, 13 or 14 digits, or a "GS1 Digital Link" URL based on such a string. The numeric component should also have a <a href="https://www.gs1.org/services/check-digit-calculator">valid GS1 check digit</a> and meet the other rules for valid GTINs. See also <a href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1's GTIN Summary</a> and <a href="https://en.wikipedia.org/wiki/Global_Trade_Item_Number">Wikipedia</a> for more details. Left-padding of the gtin values is not required or encouraged.
   */
  public String gtin;

  /**
   * The GTIN-12 code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See <a href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN Summary</a> for more details.
   */
  public String gtin12;

  /**
   * The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero. See <a href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN Summary</a> for more details.
   */
  public String gtin13;

  /**
   * The GTIN-14 code of the product, or the product to which the offer refers. See <a href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN Summary</a> for more details.
   */
  public String gtin14;

  /**
   * The GTIN-8 code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See <a href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN Summary</a> for more details.
   */
  public String gtin8;

  /**
   * Used to tag an item to be intended or suitable for consumption or use by adults only.
   */
  public AdultOrientedEnumeration hasAdultConsideration;

  /**
   * Defines the energy efficiency Category (also known as "class" or "rating") for a product according to an international energy efficiency standard.
   */
  public EnergyConsumptionDetails hasEnergyConsumptionDetails;

  /**
   * A product measurement, for example the inseam of pants, the wheel size of a bicycle, or the gauge of a screw. Usually an exact measurement, but can also be a range of measurements for adjustable products, for example belts and ski bindings.
   */
  public QuantitativeValue hasMeasurement;

  /**
   * Specifies a MerchantReturnPolicy that may be applicable.
   */
  public MerchantReturnPolicy hasMerchantReturnPolicy;

  /**
   * The height of the item.
   */
  public Distance height;

  /**
   * The height of the item.
   */
  public QuantitativeValue heightQuantitativeValue;

  /**
   * Indicates the <a class="localLink" href="https://schema.org/productGroupID">productGroupID</a> for a <a class="localLink" href="https://schema.org/ProductGroup">ProductGroup</a> that this product <a class="localLink" href="https://schema.org/isVariantOf">isVariantOf</a>.
   */
  public String inProductGroupWithID;

  /**
   * A pointer to another product (or multiple products) for which this product is an accessory or spare part.
   */
  public Product isAccessoryOrSparePartFor;

  /**
   * A pointer to another product (or multiple products) for which this product is a consumable.
   */
  public Product isConsumableFor;

  /**
   * A pointer to another, somehow related product (or multiple products).
   */
  public Service isRelatedTo;

  /**
   * A pointer to another, somehow related product (or multiple products).
   */
  public Product isRelatedToProduct;

  /**
   * A pointer to another, functionally similar product (or multiple products).
   */
  public Service isSimilarTo;

  /**
   * A pointer to another, functionally similar product (or multiple products).
   */
  public Product isSimilarToProduct;

  /**
   * Indicates the kind of product that this is a variant of. In the case of <a class="localLink" href="https://schema.org/ProductModel">ProductModel</a>, this is a pointer (from a ProductModel) to a base product from which this product is a variant. It is safe to infer that the variant inherits all product features from the base model, unless defined locally. This is not transitive. In the case of a <a class="localLink" href="https://schema.org/ProductGroup">ProductGroup</a>, the group description also serves as a template, representing a set of Products that vary on explicitly defined, specific dimensions only (so it defines both a set of variants, as well as which values distinguish amongst those variants). When used with <a class="localLink" href="https://schema.org/ProductGroup">ProductGroup</a>, this property can apply to any <a class="localLink" href="https://schema.org/Product">Product</a> included in the group.
   */
  public ProductModel isVariantOf;

  /**
   * Indicates the kind of product that this is a variant of. In the case of <a class="localLink" href="https://schema.org/ProductModel">ProductModel</a>, this is a pointer (from a ProductModel) to a base product from which this product is a variant. It is safe to infer that the variant inherits all product features from the base model, unless defined locally. This is not transitive. In the case of a <a class="localLink" href="https://schema.org/ProductGroup">ProductGroup</a>, the group description also serves as a template, representing a set of Products that vary on explicitly defined, specific dimensions only (so it defines both a set of variants, as well as which values distinguish amongst those variants). When used with <a class="localLink" href="https://schema.org/ProductGroup">ProductGroup</a>, this property can apply to any <a class="localLink" href="https://schema.org/Product">Product</a> included in the group.
   */
  public ProductGroup isVariantOfProductGroup;

  /**
   * A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.
   */
  public OfferItemCondition itemCondition;

  /**
   * Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.
   */
  public DefinedTerm keywords;

  /**
   * An associated logo.
   */
  public ImageObject logo;

  /**
   * The manufacturer of the product.
   */
  public Organization manufacturer;

  /**
   * A material that something is made from, e.g. leather, wool, cotton, paper.
   */
  public Product material;

  /**
   * The model of the product. Use with the URL of a ProductModel or a textual representation of the model identifier. The URL of the ProductModel can be from an external source. It is recommended to additionally provide strong product identifiers via the gtin8/gtin13/gtin14 and mpn properties.
   */
  public ProductModel model;

  /**
   * The Manufacturer Part Number (MPN) of the product, or the product to which the offer refers.
   */
  public String mpn;

  /**
   * Indicates the <a href="https://en.wikipedia.org/wiki/NATO_Stock_Number">NATO stock number</a> (nsn) of a <a class="localLink" href="https://schema.org/Product">Product</a>.
   */
  public String nsn;

  /**
   * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use <a class="localLink" href="https://schema.org/businessFunction">businessFunction</a> to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a <a class="localLink" href="https://schema.org/Demand">Demand</a>. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
   */
  public Offer offers;

  /**
   * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use <a class="localLink" href="https://schema.org/businessFunction">businessFunction</a> to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a <a class="localLink" href="https://schema.org/Demand">Demand</a>. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
   */
  public Demand offersDemand;

  /**
   * A pattern that something has, for example 'polka dot', 'striped', 'Canadian flag'. Values are typically expressed as text, although links to controlled value schemes are also supported.
   */
  public DefinedTerm pattern;

  /**
   * The product identifier, such as ISBN. For example: <code>meta itemprop="productID" content="isbn:123-456-789"</code>.
   */
  public String productID;

  /**
   * A review of the item.
   */
  public Review review;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public SizeSpecification size;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public QuantitativeValue sizeQuantitativeValue;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public DefinedTerm sizeDefinedTerm;

  /**
   * The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.
   */
  public String sku;

  /**
   * A slogan or motto associated with the item.
   */
  public String slogan;

  /**
   * The weight of the product or person.
   */
  public QuantitativeValue weight;

  /**
   * The width of the item.
   */
  public QuantitativeValue width;

  /**
   * The width of the item.
   */
  public Distance widthDistance;

  /**
   * Indicates whether this content is family friendly.
   */
  public Boolean isFamilyFriendly;

  /**
   * The date of production of the item, e.g. vehicle.
   */
  public ZonedDateTime productionDate;

  /**
   * The date the item e.g. vehicle was purchased by the current owner.
   */
  public ZonedDateTime purchaseDate;

  /**
   * The release date of a product or product model. This can be used to distinguish the exact variant of a product.
   */
  public ZonedDateTime releaseDate;
}

