package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * Property
 *
 * A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Property extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://meta.schema.org/Property";

  /**
   * Relates a property to a class that is (one of) the type(s) the property is expected to be used on.
   */
  public Class domainIncludes;

  /**
   * Relates a property to a property that is its inverse. Inverse properties relate the same pairs of items to each other, but in reversed direction. For example, the 'alumni' and 'alumniOf' properties are inverseOf each other. Some properties don't have explicit inverses; in these situations RDFa and JSON-LD syntax for reverse properties can be used.
   */
  public Property inverseOf;

  /**
   * Relates a property to a class that constitutes (one of) the expected type(s) for values of the property.
   */
  public Class rangeIncludes;

  /**
   * Relates a term (i.e. a property, class or enumeration) to one that supersedes it.
   */
  public Class supersededBy;

  /**
   * Relates a term (i.e. a property, class or enumeration) to one that supersedes it.
   */
  public Enumeration supersededByEnumeration;

  /**
   * Relates a term (i.e. a property, class or enumeration) to one that supersedes it.
   */
  public Property supersededByProperty;
}

