package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * RepaymentSpecification
 *
 * A structured value representing repayment.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class RepaymentSpecification extends StructuredValue {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/RepaymentSpecification";

  /**
   * a type of payment made in cash during the onset of the purchase of an expensive good/service. The payment typically represents only a percentage of the full purchase price.
   */
  public BigDecimal downPayment;

  /**
   * a type of payment made in cash during the onset of the purchase of an expensive good/service. The payment typically represents only a percentage of the full purchase price.
   */
  public MonetaryAmount downPaymentMonetaryAmount;

  /**
   * The amount to be paid as a penalty in the event of early payment of the loan.
   */
  public MonetaryAmount earlyPrepaymentPenalty;

  /**
   * The amount of money to pay in a single payment.
   */
  public MonetaryAmount loanPaymentAmount;

  /**
   * Frequency of payments due, i.e. number of months between payments. This is defined as a frequency, i.e. the reciprocal of a period of time.
   */
  public BigDecimal loanPaymentFrequency;

  /**
   * The number of payments contractually required at origination to repay the loan. For monthly paying loans this is the number of months from the contractual first payment date to the maturity date.
   */
  public BigDecimal numberOfLoanPayments;
}

