package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * Substance
 *
 * Any matter of defined composition that has discrete existence, whose origin may be biological, mineral or chemical.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Substance extends MedicalEntity {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/Substance";

  /**
   * An active ingredient, typically chemical compounds and/or biologic substances.
   */
  public String activeIngredient;

  /**
   * Recommended intake of this supplement for a given population as defined by a specific recommending authority.
   */
  public MaximumDoseSchedule maximumIntake;
}

