package uk.co.polycode.schemaorg.org.schema;

import java.lang.String;

/**
 * WebContent
 *
 * WebContent is a type representing all <a class="localLink" href="https://schema.org/WebPage">WebPage</a>, <a class="localLink" href="https://schema.org/WebSite">WebSite</a> and <a class="localLink" href="https://schema.org/WebPageElement">WebPageElement</a> content. It is sometimes the case that detailed distinctions between Web pages, sites and their parts is not always important or obvious. The  <a class="localLink" href="https://schema.org/WebContent">WebContent</a> type makes it easier to describe Web-addressable content without requiring such distinctions to always be stated. (The intent is that the existing types <a class="localLink" href="https://schema.org/WebPage">WebPage</a>, <a class="localLink" href="https://schema.org/WebSite">WebSite</a> and <a class="localLink" href="https://schema.org/WebPageElement">WebPageElement</a> will eventually be declared as subtypes of <a class="localLink" href="https://schema.org/WebContent">WebContent</a>).
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class WebContent extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/WebContent";
}

