package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigInteger;

/**
 * AggregateRating
 *
 * The average rating based on multiple ratings or reviews.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class AggregateRating extends Rating {
  /**
   * The item that is being reviewed/rated.
   */
  public Thing itemReviewed;

  /**
   * The count of total number of ratings.
   */
  public BigInteger ratingCount;

  /**
   * The count of total number of reviews.
   */
  public BigInteger reviewCount;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/AggregateRating";
}

