package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.net.URL;

/**
 * AlignmentObject
 *
 * An intangible item that describes an alignment between a learning resource and a node in an educational framework.<br/><br/>
 *
 * Should not be used where the nature of the alignment can be described using a simple property, for example to express that a resource <a class="localLink" href="https://schema.org/teaches">teaches</a> or <a class="localLink" href="https://schema.org/assesses">assesses</a> a competency.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class AlignmentObject extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/AlignmentObject";

  /**
   * A category of alignment between the learning resource and the framework node. Recommended values include: 'requires', 'textComplexity', 'readingLevel', and 'educationalSubject'.
   */
  public String alignmentType;

  /**
   * The framework to which the resource being described is aligned.
   */
  public String educationalFramework;

  /**
   * The description of a node in an established educational framework.
   */
  public String targetDescription;

  /**
   * The name of a node in an established educational framework.
   */
  public String targetName;

  /**
   * The URL of a node in an established educational framework.
   */
  public URL targetUrl;
}

