package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * AnatomicalStructure
 *
 * Any part of the human body, typically a component of an anatomical system. Organs, tissues, and cells are all anatomical structures.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class AnatomicalStructure extends MedicalEntity {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/AnatomicalStructure";

  /**
   * If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
   */
  public String associatedPathophysiology;

  /**
   * Location in the body of the anatomical structure.
   */
  public String bodyLocation;

  /**
   * Other anatomical structures to which this structure is connected.
   */
  public AnatomicalStructure connectedTo;

  /**
   * An image containing a diagram that illustrates the structure and/or its component substructures and/or connections with other structures.
   */
  public ImageObject diagram;

  /**
   * The anatomical or organ system that this structure is part of.
   */
  public AnatomicalSystem partOfSystem;

  /**
   * A medical condition associated with this anatomy.
   */
  public MedicalCondition relatedCondition;

  /**
   * A medical therapy related to this anatomy.
   */
  public MedicalTherapy relatedTherapy;

  /**
   * Component (sub-)structure(s) that comprise this anatomical structure.
   */
  public AnatomicalStructure subStructure;
}

