package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * Audience
 *
 * Intended audience for an item, i.e. the group for whom the item was created.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Audience extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Audience";

  /**
   * The target group associated with a given audience (e.g. veterans, car owners, musicians, etc.).
   */
  public String audienceType;

  /**
   * The geographic area associated with the audience.
   */
  public AdministrativeArea geographicArea;
}

