package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * BioChemEntity
 *
 * Any biological, chemical, or biochemical thing. For example: a protein; a gene; a chemical; a synthetic chemical.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BioChemEntity extends Thing {
  /**
   * Disease associated to this BioChemEntity. Such disease can be a MedicalCondition or a URL. If you want to add an evidence supporting the association, please use PropertyValue.
   */
  public PropertyValue associatedDiseasePropertyValue;

  /**
   * Disease associated to this BioChemEntity. Such disease can be a MedicalCondition or a URL. If you want to add an evidence supporting the association, please use PropertyValue.
   */
  public MedicalCondition associatedDisease;

  /**
   * A BioChemEntity that is known to interact with this item.
   */
  public BioChemEntity bioChemInteraction;

  /**
   * A similar BioChemEntity, e.g., obtained by fingerprint similarity algorithms.
   */
  public BioChemEntity bioChemSimilarity;

  /**
   * A role played by the BioChemEntity within a biological context.
   */
  public DefinedTerm biologicalRole;

  /**
   * A <a class="localLink" href="https://schema.org/Grant">Grant</a> that directly or indirectly provide funding or sponsorship for this item. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Grant funding;

  /**
   * Indicates a BioChemEntity that (in some sense) has this BioChemEntity as a part.
   */
  public BioChemEntity hasBioChemEntityPart;

  /**
   * Molecular function performed by this BioChemEntity; please use PropertyValue if you want to include any evidence.
   */
  public DefinedTerm hasMolecularFunctionDefinedTerm;

  /**
   * Molecular function performed by this BioChemEntity; please use PropertyValue if you want to include any evidence.
   */
  public PropertyValue hasMolecularFunction;

  /**
   * A common representation such as a protein sequence or chemical structure for this entity. For images use schema.org/image.
   */
  public PropertyValue hasRepresentation;

  /**
   * Another BioChemEntity encoding by this one.
   */
  public Gene isEncodedByBioChemEntity;

  /**
   * Biological process this BioChemEntity is involved in; please use PropertyValue if you want to include any evidence.
   */
  public PropertyValue isInvolvedInBiologicalProcessPropertyValue;

  /**
   * Biological process this BioChemEntity is involved in; please use PropertyValue if you want to include any evidence.
   */
  public DefinedTerm isInvolvedInBiologicalProcess;

  /**
   * Subcellular location where this BioChemEntity is located; please use PropertyValue if you want to include any evidence.
   */
  public DefinedTerm isLocatedInSubcellularLocationDefinedTerm;

  /**
   * Subcellular location where this BioChemEntity is located; please use PropertyValue if you want to include any evidence.
   */
  public PropertyValue isLocatedInSubcellularLocation;

  /**
   * Indicates a BioChemEntity that is (in some sense) a part of this BioChemEntity.
   */
  public BioChemEntity isPartOfBioChemEntity;

  /**
   * The taxonomic grouping of the organism that expresses, encodes, or in someway related to the BioChemEntity.
   */
  public DefinedTerm taxonomicRangeDefinedTerm;

  /**
   * The taxonomic grouping of the organism that expresses, encodes, or in someway related to the BioChemEntity.
   */
  public Taxon taxonomicRange;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/BioChemEntity";
}

