package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * BroadcastFrequencySpecification
 *
 * The frequency in MHz and the modulation used for a particular BroadcastService.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BroadcastFrequencySpecification extends Intangible {
  /**
   * The frequency in MHz for a particular broadcast.
   */
  public QuantitativeValue broadcastFrequencyValueQuantitativeValue;

  /**
   * The frequency in MHz for a particular broadcast.
   */
  public BigDecimal broadcastFrequencyValue;

  /**
   * The modulation (e.g. FM, AM, etc) used by a particular broadcast service.
   */
  public QualitativeValue broadcastSignalModulation;

  /**
   * The subchannel used for the broadcast.
   */
  public String broadcastSubChannel;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/BroadcastFrequencySpecification";
}

