package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * BroadcastService
 *
 * A delivery service through which content is provided via broadcast over the air or online.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BroadcastService extends Service {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/BroadcastService";

  /**
   * The media network(s) whose content is broadcast on this station.
   */
  public Organization broadcastAffiliateOf;

  /**
   * The name displayed in the channel guide. For many US affiliates, it is the network name.
   */
  public String broadcastDisplayName;

  /**
   * The frequency used for over-the-air broadcasts. Numeric values or simple ranges e.g. 87-99. In addition a shortcut idiom is supported for frequences of AM and FM radio channels, e.g. "87 FM".
   */
  public BroadcastFrequencySpecification broadcastFrequency;

  /**
   * The timezone in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 format</a> for which the service bases its broadcasts
   */
  public String broadcastTimezone;

  /**
   * The organization owning or operating the broadcast service.
   */
  public Organization broadcaster;

  /**
   * A <a href="https://en.wikipedia.org/wiki/Call_sign">callsign</a>, as used in broadcasting and radio communications to identify people, radio and TV stations, or vehicles.
   */
  public String callSign;

  /**
   * A broadcast channel of a broadcast service.
   */
  public BroadcastChannel hasBroadcastChannel;

  /**
   * The language of the content or performance or used in an action. Please use one of the language codes from the <a href="http://tools.ietf.org/html/bcp47">IETF BCP 47 standard</a>. See also <a class="localLink" href="https://schema.org/availableLanguage">availableLanguage</a>.
   */
  public Language inLanguage;

  /**
   * A broadcast service to which the broadcast service may belong to such as regional variations of a national channel.
   */
  public BroadcastService parentService;

  /**
   * The type of screening or video broadcast used (e.g. IMAX, 3D, SD, HD, etc.).
   */
  public String videoFormat;
}

