package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * BroadcastChannel
 *
 * A unique instance of a BroadcastService on a CableOrSatelliteService lineup.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BroadcastChannel extends Intangible {
  /**
   * The unique address by which the BroadcastService can be identified in a provider lineup. In US, this is typically a number.
   */
  public String broadcastChannelId;

  /**
   * The frequency used for over-the-air broadcasts. Numeric values or simple ranges e.g. 87-99. In addition a shortcut idiom is supported for frequences of AM and FM radio channels, e.g. "87 FM".
   */
  public BroadcastFrequencySpecification broadcastFrequency;

  /**
   * The type of service required to have access to the channel (e.g. Standard or Premium).
   */
  public String broadcastServiceTier;

  /**
   * Genre of the creative work, broadcast channel or group.
   */
  public String genre;

  /**
   * The CableOrSatelliteService offering the channel.
   */
  public CableOrSatelliteService inBroadcastLineup;

  /**
   * The BroadcastService offered on this channel.
   */
  public BroadcastService providesBroadcastService;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/BroadcastChannel";
}

