package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * BusinessFunction
 *
 * The business function specifies the type of activity or access (i.e., the bundle of rights) offered by the organization or business person through the offer. Typical are sell, rental or lease, maintenance or repair, manufacture / produce, recycle / dispose, engineering / construction, or installation. Proprietary specifications of access rights are also instances of this class.<br/><br/>
 *
 * Commonly used values:<br/><br/>
 *
 * <ul>
 * <li>http://purl.org/goodrelations/v1#ConstructionInstallation</li>
 * <li>http://purl.org/goodrelations/v1#Dispose</li>
 * <li>http://purl.org/goodrelations/v1#LeaseOut</li>
 * <li>http://purl.org/goodrelations/v1#Maintain</li>
 * <li>http://purl.org/goodrelations/v1#ProvideService</li>
 * <li>http://purl.org/goodrelations/v1#Repair</li>
 * <li>http://purl.org/goodrelations/v1#Sell</li>
 * <li>http://purl.org/goodrelations/v1#Buy</li>
 * </ul>
 *
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class BusinessFunction extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/BusinessFunction";
}

