package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.URL;
import java.time.ZonedDateTime;

/**
 * CreativeWork
 *
 * The most generic kind of creative work, including books, movies, photographs, software programs, etc.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class CreativeWork extends Thing {
  /**
   * The subject matter of the content.
   */
  public Thing about;

  /**
   * An abstract is a short description that summarizes a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>.
   */
  public String abstractField;

  /**
   * The human sensory perceptual system or cognitive faculty through which a person may process or perceive information. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessMode-vocabulary">approved vocabulary</a>.
   */
  public String accessMode;

  /**
   * A list of single or combined accessModes that are sufficient to understand all the intellectual content of a resource. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessModeSufficient-vocabulary">approved vocabulary</a>.
   */
  public ItemList accessModeSufficient;

  /**
   * Indicates that the resource is compatible with the referenced accessibility API. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityAPI-vocabulary">approved vocabulary</a>.
   */
  public String accessibilityAPI;

  /**
   * Identifies input methods that are sufficient to fully control the described resource. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityControl-vocabulary">approved vocabulary</a>.
   */
  public String accessibilityControl;

  /**
   * Content features of the resource, such as accessible media, alternatives and supported enhancements for accessibility. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityFeature-vocabulary">approved vocabulary</a>.
   */
  public String accessibilityFeature;

  /**
   * A characteristic of the described resource that is physiologically dangerous to some users. Related to WCAG 2.0 guideline 2.3. Values should be drawn from the <a href="https://www.w3.org/2021/a11y-discov-vocab/latest/#accessibilityHazard-vocabulary">approved vocabulary</a>.
   */
  public String accessibilityHazard;

  /**
   * A human-readable summary of specific accessibility features or deficiencies, consistent with the other accessibility metadata but expressing subtleties such as "short descriptions are present but long descriptions will be needed for non-visual users" or "short descriptions are present and no long descriptions are needed."
   */
  public String accessibilitySummary;

  /**
   * Specifies the Person that is legally accountable for the CreativeWork.
   */
  public Person accountablePerson;

  /**
   * Indicates a page documenting how licenses can be purchased or otherwise acquired, for the current item.
   */
  public CreativeWork acquireLicensePage;

  /**
   * The overall rating, based on a collection of reviews or ratings, of the item.
   */
  public AggregateRating aggregateRating;

  /**
   * A secondary title of the CreativeWork.
   */
  public String alternativeHeadline;

  /**
   * Indicates a page or other link involved in archival of a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>. In the case of <a class="localLink" href="https://schema.org/MediaReview">MediaReview</a>, the items in a <a class="localLink" href="https://schema.org/MediaReviewItem">MediaReviewItem</a> may often become inaccessible, but be archived by archival, journalistic, activist, or law enforcement organizations. In such cases, the referenced page may not directly publish the content.
   */
  public WebPage archivedAt;

  /**
   * The item being described is intended to assess the competency or learning outcome defined by the referenced term.
   */
  public DefinedTerm assesses;

  /**
   * A media object that encodes this CreativeWork. This property is a synonym for encoding.
   */
  public MediaObject associatedMedia;

  /**
   * An intended audience, i.e. a group for whom something was created.
   */
  public Audience audience;

  /**
   * An embedded audio object.
   */
  public Clip audioClip;

  /**
   * An embedded audio object.
   */
  public MusicRecording audioMusicRecording;

  /**
   * An embedded audio object.
   */
  public AudioObject audio;

  /**
   * The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
   */
  public Organization authorOrganization;

  /**
   * The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
   */
  public Person author;

  /**
   * An award won by or for this item.
   */
  public String award;

  /**
   * Fictional person connected with a creative work.
   */
  public Person character;

  /**
   * A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.
   */
  public CreativeWork citation;

  /**
   * Comments, typically from users.
   */
  public Comment comment;

  /**
   * Conditions that affect the availability of, or method(s) of access to, an item. Typically used for real world items such as an <a class="localLink" href="https://schema.org/ArchiveComponent">ArchiveComponent</a> held by an <a class="localLink" href="https://schema.org/ArchiveOrganization">ArchiveOrganization</a>. This property is not suitable for use as a general Web access control mechanism. It is expressed only in natural language.<br/><br/>
   *
   * For example "Available by appointment from the Reading Room" or "Accessible only from logged-in accounts ".
   */
  public String conditionsOfAccess;

  /**
   * The location depicted or described in the content. For example, the location in a photograph or painting.
   */
  public Place contentLocation;

  /**
   * Official rating of a piece of content&#x2014;for example,'MPAA PG-13'.
   */
  public Rating contentRating;

  /**
   * A secondary contributor to the CreativeWork or Event.
   */
  public Organization contributorOrganization;

  /**
   * A secondary contributor to the CreativeWork or Event.
   */
  public Person contributor;

  /**
   * The party holding the legal copyright to the CreativeWork.
   */
  public Organization copyrightHolderOrganization;

  /**
   * The party holding the legal copyright to the CreativeWork.
   */
  public Person copyrightHolder;

  /**
   * Text of a notice appropriate for describing the copyright aspects of this Creative Work, ideally indicating the owner of the copyright for the Work.
   */
  public String copyrightNotice;

  /**
   * Indicates a correction to a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>, either via a <a class="localLink" href="https://schema.org/CorrectionComment">CorrectionComment</a>, textually or in another document.
   */
  public CorrectionComment correction;

  /**
   * The country of origin of something, including products as well as creative  works such as movie and TV content.<br/><br/>
   *
   * In the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other kinds of <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a> it is difficult to provide fully general guidance, and properties such as <a class="localLink" href="https://schema.org/contentLocation">contentLocation</a> and <a class="localLink" href="https://schema.org/locationCreated">locationCreated</a> may be more applicable.<br/><br/>
   *
   * In the case of products, the country of origin of the product. The exact interpretation of this may vary by context and product type, and cannot be fully enumerated here.
   */
  public Country countryOfOrigin;

  /**
   * The status of a creative work in terms of its stage in a lifecycle. Example terms include Incomplete, Draft, Published, Obsolete. Some organizations define a set of terms for the stages of their publication lifecycle.
   */
  public DefinedTerm creativeWorkStatus;

  /**
   * The creator/author of this CreativeWork. This is the same as the Author property for CreativeWork.
   */
  public Organization creatorOrganization;

  /**
   * The creator/author of this CreativeWork. This is the same as the Author property for CreativeWork.
   */
  public Person creator;

  /**
   * Text that can be used to credit person(s) and/or organization(s) associated with a published Creative Work.
   */
  public String creditText;

  /**
   * A link to the page containing the comments of the CreativeWork.
   */
  public URL discussionUrl;

  /**
   * An <a href="https://eidr.org/">EIDR</a> (Entertainment Identifier Registry) <a class="localLink" href="https://schema.org/identifier">identifier</a> representing a specific edit / edition for a work of film or television.<br/><br/>
   *
   * For example, the motion picture known as "Ghostbusters" whose <a class="localLink" href="https://schema.org/titleEIDR">titleEIDR</a> is "10.5240/7EC7-228A-510A-053E-CBB8-J", has several edits e.g. "10.5240/1F2A-E1C5-680A-14C6-E76B-I" and "10.5240/8A35-3BEE-6497-5D12-9E4F-3".<br/><br/>
   *
   * Since schema.org types like <a class="localLink" href="https://schema.org/Movie">Movie</a> and <a class="localLink" href="https://schema.org/TVEpisode">TVEpisode</a> can be used for both works and their multiple expressions, it is possible to use <a class="localLink" href="https://schema.org/titleEIDR">titleEIDR</a> alone (for a general description), or alongside <a class="localLink" href="https://schema.org/editEIDR">editEIDR</a> for a more edit-specific description.
   */
  public String editEIDR;

  /**
   * Specifies the Person who edited the CreativeWork.
   */
  public Person editor;

  /**
   * An alignment to an established educational framework.<br/><br/>
   *
   * This property should not be used where the nature of the alignment can be described using a simple property, for example to express that a resource <a class="localLink" href="https://schema.org/teaches">teaches</a> or <a class="localLink" href="https://schema.org/assesses">assesses</a> a competency.
   */
  public AlignmentObject educationalAlignment;

  /**
   * The level in terms of progression through an educational or training context. Examples of educational levels include 'beginner', 'intermediate' or 'advanced', and formal sets of level indicators.
   */
  public DefinedTerm educationalLevel;

  /**
   * The purpose of a work in the context of education; for example, 'assignment', 'group work'.
   */
  public DefinedTerm educationalUse;

  /**
   * A media object that encodes this CreativeWork. This property is a synonym for associatedMedia.
   */
  public MediaObject encoding;

  /**
   * Media type typically expressed using a MIME format (see <a href="http://www.iana.org/assignments/media-types/media-types.xhtml">IANA site</a> and <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types">MDN reference</a>) e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.).<br/><br/>
   *
   * In cases where a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a> has several media type representations, <a class="localLink" href="https://schema.org/encoding">encoding</a> can be used to indicate each <a class="localLink" href="https://schema.org/MediaObject">MediaObject</a> alongside particular <a class="localLink" href="https://schema.org/encodingFormat">encodingFormat</a> information.<br/><br/>
   *
   * Unregistered or niche encoding and file formats can be indicated instead via the most appropriate URL, e.g. defining Web page or a Wikipedia/Wikidata entry.
   */
  public String encodingFormat;

  /**
   * A creative work that this work is an example/instance/realization/derivation of.
   */
  public CreativeWork exampleOfWork;

  /**
   * A person or organization that supports (sponsors) something through some kind of financial contribution.
   */
  public Organization funderOrganization;

  /**
   * A person or organization that supports (sponsors) something through some kind of financial contribution.
   */
  public Person funder;

  /**
   * A <a class="localLink" href="https://schema.org/Grant">Grant</a> that directly or indirectly provide funding or sponsorship for this item. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Grant funding;

  /**
   * Genre of the creative work, broadcast channel or group.
   */
  public String genre;

  /**
   * Indicates an item or CreativeWork that is part of this item, or CreativeWork (in some sense).
   */
  public CreativeWork hasPart;

  /**
   * Headline of the article.
   */
  public String headline;

  /**
   * The language of the content or performance or used in an action. Please use one of the language codes from the <a href="http://tools.ietf.org/html/bcp47">IETF BCP 47 standard</a>. See also <a class="localLink" href="https://schema.org/availableLanguage">availableLanguage</a>.
   */
  public Language inLanguage;

  /**
   * The number of interactions for the CreativeWork using the WebSite or SoftwareApplication. The most specific child type of InteractionCounter should be used.
   */
  public InteractionCounter interactionStatistic;

  /**
   * The predominant mode of learning supported by the learning resource. Acceptable values are 'active', 'expositive', or 'mixed'.
   */
  public String interactivityType;

  /**
   * Used to indicate a specific claim contained, implied, translated or refined from the content of a <a class="localLink" href="https://schema.org/MediaObject">MediaObject</a> or other <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>. The interpreting party can be indicated using <a class="localLink" href="https://schema.org/claimInterpreter">claimInterpreter</a>.
   */
  public Claim interpretedAsClaim;

  /**
   * A resource from which this work is derived or from which it is a modification or adaption.
   */
  public Product isBasedOnProduct;

  /**
   * A resource from which this work is derived or from which it is a modification or adaption.
   */
  public CreativeWork isBasedOn;

  /**
   * Indicates an item or CreativeWork that this item, or CreativeWork (in some sense), is part of.
   */
  public CreativeWork isPartOf;

  /**
   * Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.
   */
  public DefinedTerm keywords;

  /**
   * The predominant type or kind characterizing the learning resource. For example, 'presentation', 'handout'.
   */
  public DefinedTerm learningResourceType;

  /**
   * A license document that applies to this content, typically indicated by URL.
   */
  public CreativeWork license;

  /**
   * The location where the CreativeWork was created, which may not be the same as the location depicted in the CreativeWork.
   */
  public Place locationCreated;

  /**
   * Indicates the primary entity described in some page or other CreativeWork.
   */
  public Thing mainEntity;

  /**
   * A maintainer of a <a class="localLink" href="https://schema.org/Dataset">Dataset</a>, software package (<a class="localLink" href="https://schema.org/SoftwareApplication">SoftwareApplication</a>), or other <a class="localLink" href="https://schema.org/Project">Project</a>. A maintainer is a <a class="localLink" href="https://schema.org/Person">Person</a> or <a class="localLink" href="https://schema.org/Organization">Organization</a> that manages contributions to, and/or publication of, some (typically complex) artifact. It is common for distributions of software and data to be based on "upstream" sources. When <a class="localLink" href="https://schema.org/maintainer">maintainer</a> is applied to a specific version of something e.g. a particular version or packaging of a <a class="localLink" href="https://schema.org/Dataset">Dataset</a>, it is always  possible that the upstream source has a different maintainer. The <a class="localLink" href="https://schema.org/isBasedOn">isBasedOn</a> property can be used to indicate such relationships between datasets to make the different maintenance roles clear. Similarly in the case of software, a package may have dedicated maintainers working on integration into software distributions such as Ubuntu, as well as upstream maintainers of the underlying work.
   */
  public Organization maintainerOrganization;

  /**
   * A maintainer of a <a class="localLink" href="https://schema.org/Dataset">Dataset</a>, software package (<a class="localLink" href="https://schema.org/SoftwareApplication">SoftwareApplication</a>), or other <a class="localLink" href="https://schema.org/Project">Project</a>. A maintainer is a <a class="localLink" href="https://schema.org/Person">Person</a> or <a class="localLink" href="https://schema.org/Organization">Organization</a> that manages contributions to, and/or publication of, some (typically complex) artifact. It is common for distributions of software and data to be based on "upstream" sources. When <a class="localLink" href="https://schema.org/maintainer">maintainer</a> is applied to a specific version of something e.g. a particular version or packaging of a <a class="localLink" href="https://schema.org/Dataset">Dataset</a>, it is always  possible that the upstream source has a different maintainer. The <a class="localLink" href="https://schema.org/isBasedOn">isBasedOn</a> property can be used to indicate such relationships between datasets to make the different maintenance roles clear. Similarly in the case of software, a package may have dedicated maintainers working on integration into software distributions such as Ubuntu, as well as upstream maintainers of the underlying work.
   */
  public Person maintainer;

  /**
   * A material that something is made from, e.g. leather, wool, cotton, paper.
   */
  public Product material;

  /**
   * The quantity of the materials being described or an expression of the physical space they occupy.
   */
  public QuantitativeValue materialExtent;

  /**
   * Indicates that the CreativeWork contains a reference to, but is not necessarily about a concept.
   */
  public Thing mentions;

  /**
   * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use <a class="localLink" href="https://schema.org/businessFunction">businessFunction</a> to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a <a class="localLink" href="https://schema.org/Demand">Demand</a>. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
   */
  public Demand offersDemand;

  /**
   * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use <a class="localLink" href="https://schema.org/businessFunction">businessFunction</a> to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a <a class="localLink" href="https://schema.org/Demand">Demand</a>. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
   */
  public Offer offers;

  /**
   * A pattern that something has, for example 'polka dot', 'striped', 'Canadian flag'. Values are typically expressed as text, although links to controlled value schemes are also supported.
   */
  public DefinedTerm pattern;

  /**
   * The position of an item in a series or sequence of items.
   */
  public BigInteger position;

  /**
   * The person or organization who produced the work (e.g. music album, movie, tv/radio series etc.).
   */
  public Organization producerOrganization;

  /**
   * The person or organization who produced the work (e.g. music album, movie, tv/radio series etc.).
   */
  public Person producer;

  /**
   * The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
   */
  public Organization providerOrganization;

  /**
   * The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
   */
  public Person provider;

  /**
   * A publication event associated with the item.
   */
  public PublicationEvent publication;

  /**
   * The publisher of the creative work.
   */
  public Organization publisherOrganization;

  /**
   * The publisher of the creative work.
   */
  public Person publisher;

  /**
   * The publishing division which published the comic.
   */
  public Organization publisherImprint;

  /**
   * The publishingPrinciples property indicates (typically via <a class="localLink" href="https://schema.org/URL">URL</a>) a document describing the editorial principles of an <a class="localLink" href="https://schema.org/Organization">Organization</a> (or individual e.g. a <a class="localLink" href="https://schema.org/Person">Person</a> writing a blog) that relate to their activities as a publisher, e.g. ethics or diversity policies. When applied to a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a> (e.g. <a class="localLink" href="https://schema.org/NewsArticle">NewsArticle</a>) the principles are those of the party primarily responsible for the creation of the <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>.<br/><br/>
   *
   * While such policies are most typically expressed in natural language, sometimes related information (e.g. indicating a <a class="localLink" href="https://schema.org/funder">funder</a>) can be expressed using schema.org terminology.
   */
  public CreativeWork publishingPrinciples;

  /**
   * The Event where the CreativeWork was recorded. The CreativeWork may capture all or part of the event.
   */
  public Event recordedAt;

  /**
   * The place and time the release was issued, expressed as a PublicationEvent.
   */
  public PublicationEvent releasedEvent;

  /**
   * A review of the item.
   */
  public Review review;

  /**
   * Indicates (by URL or string) a particular version of a schema used in some CreativeWork. This property was created primarily to
   *     indicate the use of a specific schema.org release, e.g. <code>10.0</code> as a simple string, or more explicitly via URL, <code>https://schema.org/docs/releases.html#v10.0</code>. There may be situations in which other schemas might usefully be referenced this way, e.g. <code>http://dublincore.org/specifications/dublin-core/dces/1999-07-02/</code> but this has not been carefully explored in the community.
   */
  public String schemaVersion;

  /**
   * A license document that applies to this structured data, typically indicated by URL.
   */
  public CreativeWork sdLicense;

  /**
   * Indicates the party responsible for generating and publishing the current structured data markup, typically in cases where the structured data is derived automatically from existing published content but published on a different site. For example, student projects and open data initiatives often re-publish existing content with more explicitly structured metadata. The
   * <a class="localLink" href="https://schema.org/sdPublisher">sdPublisher</a> property helps make such practices more explicit.
   */
  public Organization sdPublisherOrganization;

  /**
   * Indicates the party responsible for generating and publishing the current structured data markup, typically in cases where the structured data is derived automatically from existing published content but published on a different site. For example, student projects and open data initiatives often re-publish existing content with more explicitly structured metadata. The
   * <a class="localLink" href="https://schema.org/sdPublisher">sdPublisher</a> property helps make such practices more explicit.
   */
  public Person sdPublisher;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public QuantitativeValue sizeQuantitativeValue;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public DefinedTerm sizeDefinedTerm;

  /**
   * A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured <a class="localLink" href="https://schema.org/SizeSpecification">SizeSpecification</a>; in other cases, the <a class="localLink" href="https://schema.org/width">width</a>, <a class="localLink" href="https://schema.org/height">height</a>, <a class="localLink" href="https://schema.org/depth">depth</a> and <a class="localLink" href="https://schema.org/weight">weight</a> properties may be more applicable.
   */
  public SizeSpecification size;

  /**
   * The Organization on whose behalf the creator was working.
   */
  public Organization sourceOrganization;

  /**
   * The "spatial" property can be used in cases when more specific properties
   * (e.g. <a class="localLink" href="https://schema.org/locationCreated">locationCreated</a>, <a class="localLink" href="https://schema.org/spatialCoverage">spatialCoverage</a>, <a class="localLink" href="https://schema.org/contentLocation">contentLocation</a>) are not known to be appropriate.
   */
  public Place spatial;

  /**
   * The spatialCoverage of a CreativeWork indicates the place(s) which are the focus of the content. It is a subproperty of
   *       contentLocation intended primarily for more technical and detailed materials. For example with a Dataset, it indicates
   *       areas that the dataset describes: a dataset of New York weather would have spatialCoverage which was the place: the state of New York.
   */
  public Place spatialCoverage;

  /**
   * A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.
   */
  public Organization sponsorOrganization;

  /**
   * A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.
   */
  public Person sponsor;

  /**
   * The item being described is intended to help a person learn the competency or learning outcome defined by the referenced term.
   */
  public DefinedTerm teaches;

  /**
   * The "temporal" property can be used in cases where more specific properties
   * (e.g. <a class="localLink" href="https://schema.org/temporalCoverage">temporalCoverage</a>, <a class="localLink" href="https://schema.org/dateCreated">dateCreated</a>, <a class="localLink" href="https://schema.org/dateModified">dateModified</a>, <a class="localLink" href="https://schema.org/datePublished">datePublished</a>) are not known to be appropriate.
   */
  public ZonedDateTime temporal;

  /**
   * The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, either as a DateTime or as a textual string indicating a time period in <a href="https://en.wikipedia.org/wiki/ISO_8601#Time_intervals">ISO 8601 time interval format</a>. In
   *       the case of a Dataset it will typically indicate the relevant time period in a precise notation (e.g. for a 2011 census dataset, the year 2011 would be written "2011/2012"). Other forms of content e.g. ScholarlyArticle, Book, TVSeries or TVEpisode may indicate their temporalCoverage in broader terms - textually or via well-known URL.
   *       Written works such as books may sometimes have precise temporal coverage too, e.g. a work set in 1939 - 1945 can be indicated in ISO 8601 interval format format via "1939/1945".<br/><br/>
   *
   * Open-ended date ranges can be written with ".." in place of the end date. For example, "2015-11/.." indicates a range beginning in November 2015 and with no specified final date. This is tentative and might be updated in future when ISO 8601 is officially updated.
   */
  public ZonedDateTime temporalCoverage;

  /**
   * The textual content of this CreativeWork.
   */
  public String text;

  /**
   * A thumbnail image relevant to the Thing.
   */
  public URL thumbnailUrl;

  /**
   * Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. 'PT30M', 'PT1H25M'.
   */
  public Duration timeRequired;

  /**
   * The work that this work has been translated from. e.g. 物种起源 is a translationOf “On the Origin of Species”
   */
  public CreativeWork translationOfWork;

  /**
   * Organization or person who adapts a creative work to different languages, regional differences and technical requirements of a target market, or that translates during some event.
   */
  public Organization translatorOrganization;

  /**
   * Organization or person who adapts a creative work to different languages, regional differences and technical requirements of a target market, or that translates during some event.
   */
  public Person translator;

  /**
   * The typical expected age range, e.g. '7-9', '11-'.
   */
  public String typicalAgeRange;

  /**
   * The schema.org <a class="localLink" href="https://schema.org/usageInfo">usageInfo</a> property indicates further information about a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>. This property is applicable both to works that are freely available and to those that require payment or other transactions. It can reference additional information e.g. community expectations on preferred linking and citation conventions, as well as purchasing details. For something that can be commercially licensed, usageInfo can provide detailed, resource-specific information about licensing options.<br/><br/>
   *
   * This property can be used alongside the license property which indicates license(s) applicable to some piece of content. The usageInfo property can provide information about other licensing options, e.g. acquiring commercial usage rights for an image that is also available under non-commercial creative commons licenses.
   */
  public CreativeWork usageInfo;

  /**
   * The version of the CreativeWork embodied by a specified resource.
   */
  public BigDecimal version;

  /**
   * An embedded video object.
   */
  public VideoObject videoVideoObject;

  /**
   * An embedded video object.
   */
  public Clip video;

  /**
   * Example/instance/realization/derivation of the concept of this creative work. eg. The paperback edition, first edition, or eBook.
   */
  public CreativeWork workExample;

  /**
   * A work that is a translation of the content of this work. e.g. 西遊記 has an English workTranslation “Journey to the West”,a German workTranslation “Monkeys Pilgerfahrt” and a Vietnamese  translation Tây du ký bình khảo.
   */
  public CreativeWork workTranslation;

  /**
   * The number of comments this CreativeWork (e.g. Article, Question or Answer) has received. This is most applicable to works published in Web sites with commenting system; additional comments may exist elsewhere.
   */
  public BigInteger commentCount;

  /**
   * The specific time described by a creative work, for works (e.g. articles, video objects etc.) that emphasise a particular moment within an Event.
   */
  public ZonedDateTime contentReferenceTime;

  /**
   * The year during which the claimed copyright for the CreativeWork was first asserted.
   */
  public BigDecimal copyrightYear;

  /**
   * The date on which the CreativeWork was created or the item was added to a DataFeed.
   */
  public ZonedDateTime dateCreatedZonedDateTime;

  /**
   * The date on which the CreativeWork was created or the item was added to a DataFeed.
   */
  public ZonedDateTime dateCreated;

  /**
   * The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
   */
  public ZonedDateTime dateModifiedZonedDateTime;

  /**
   * The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
   */
  public ZonedDateTime dateModified;

  /**
   * Date of first broadcast/publication.
   */
  public ZonedDateTime datePublishedZonedDateTime;

  /**
   * Date of first broadcast/publication.
   */
  public ZonedDateTime datePublished;

  /**
   * Date the content expires and is no longer useful or available. For example a <a class="localLink" href="https://schema.org/VideoObject">VideoObject</a> or <a class="localLink" href="https://schema.org/NewsArticle">NewsArticle</a> whose availability or relevance is time-limited, or a <a class="localLink" href="https://schema.org/ClaimReview">ClaimReview</a> fact check whose publisher wants to indicate that it may no longer be relevant (or helpful to highlight) after some date.
   */
  public ZonedDateTime expires;

  /**
   * A flag to signal that the item, event, or place is accessible for free.
   */
  public Boolean isAccessibleForFree;

  /**
   * Indicates whether this content is family friendly.
   */
  public Boolean isFamilyFriendly;

  /**
   * Indicates the date on which the current structured data was generated / published. Typically used alongside <a class="localLink" href="https://schema.org/sdPublisher">sdPublisher</a>
   */
  public ZonedDateTime sdDatePublished;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/CreativeWork";
}

