package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DayOfWeek
 *
 * The day of the week, e.g. used to specify to which day the opening hours of an OpeningHoursSpecification refer.<br/><br/>
 *
 * Originally, URLs from <a href="http://purl.org/goodrelations/v1">GoodRelations</a> were used (for <a class="localLink" href="https://schema.org/Monday">Monday</a>, <a class="localLink" href="https://schema.org/Tuesday">Tuesday</a>, <a class="localLink" href="https://schema.org/Wednesday">Wednesday</a>, <a class="localLink" href="https://schema.org/Thursday">Thursday</a>, <a class="localLink" href="https://schema.org/Friday">Friday</a>, <a class="localLink" href="https://schema.org/Saturday">Saturday</a>, <a class="localLink" href="https://schema.org/Sunday">Sunday</a> plus a special entry for <a class="localLink" href="https://schema.org/PublicHolidays">PublicHolidays</a>); these have now been integrated directly into schema.org.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DayOfWeek extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/DayOfWeek";
}

