package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DDxElement
 *
 * An alternative, closely-related condition typically considered later in the differential diagnosis process along with the signs that are used to distinguish it.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DDxElement extends MedicalIntangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/DDxElement";

  /**
   * One or more alternative conditions considered in the differential diagnosis process as output of a diagnosis process.
   */
  public MedicalCondition diagnosis;

  /**
   * One of a set of signs and symptoms that can be used to distinguish this diagnosis from others in the differential diagnosis.
   */
  public MedicalSignOrSymptom distinguishingSign;
}

