package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DefinedRegion
 *
 * A DefinedRegion is a geographic area defined by potentially arbitrary (rather than political, administrative or natural geographical) criteria. Properties are provided for defining a region by reference to sets of postal codes.<br/><br/>
 *
 * Examples: a delivery destination when shopping. Region where regional pricing is configured.<br/><br/>
 *
 * Requirement 1:
 * Country: US
 * States: "NY", "CA"<br/><br/>
 *
 * Requirement 2:
 * Country: US
 * PostalCode Set: { [94000-94585], [97000, 97999], [13000, 13599]}
 * { [12345, 12345], [78945, 78945], }
 * Region = state, canton, prefecture, autonomous community...
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DefinedRegion extends StructuredValue {
  /**
   * The country. For example, USA. You can also provide the two-letter <a href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166-1 alpha-2 country code</a>.
   */
  public Country addressCountry;

  /**
   * The region in which the locality is, and which is in the country. For example, California or another appropriate first-level <a href="https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country">Administrative division</a>
   */
  public String addressRegion;

  /**
   * The postal code. For example, 94043.
   */
  public String postalCode;

  /**
   * A defined range of postal codes indicated by a common textual prefix. Used for non-numeric systems such as UK.
   */
  public String postalCodePrefix;

  /**
   * A defined range of postal codes.
   */
  public PostalCodeRangeSpecification postalCodeRange;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/DefinedRegion";
}

