package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DefinedTerm
 *
 * A word, name, acronym, phrase, etc. with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property for the term being defined, use termCode if the term has an alpha-numeric code allocated, use description to provide the definition of the term.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DefinedTerm extends Intangible {
  /**
   * A <a class="localLink" href="https://schema.org/DefinedTermSet">DefinedTermSet</a> that contains this term.
   */
  public DefinedTermSet inDefinedTermSet;

  /**
   * A code that identifies this <a class="localLink" href="https://schema.org/DefinedTerm">DefinedTerm</a> within a <a class="localLink" href="https://schema.org/DefinedTermSet">DefinedTermSet</a>
   */
  public String termCode;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/DefinedTerm";
}

