package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DeliveryMethod
 *
 * A delivery method is a standardized procedure for transferring the product or service to the destination of fulfillment chosen by the customer. Delivery methods are characterized by the means of transportation used, and by the organization or group that is the contracting party for the sending organization or person.<br/><br/>
 *
 * Commonly used values:<br/><br/>
 *
 * <ul>
 * <li>http://purl.org/goodrelations/v1#DeliveryModeDirectDownload</li>
 * <li>http://purl.org/goodrelations/v1#DeliveryModeFreight</li>
 * <li>http://purl.org/goodrelations/v1#DeliveryModeMail</li>
 * <li>http://purl.org/goodrelations/v1#DeliveryModeOwnFleet</li>
 * <li>http://purl.org/goodrelations/v1#DeliveryModePickUp</li>
 * <li>http://purl.org/goodrelations/v1#DHL</li>
 * <li>http://purl.org/goodrelations/v1#FederalExpress</li>
 * <li>http://purl.org/goodrelations/v1#UPS</li>
 * </ul>
 *
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DeliveryMethod extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/DeliveryMethod";
}

