package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * DigitalPlatformEnumeration
 *
 * Enumerates some common technology platforms, for use with properties such as <a class="localLink" href="https://schema.org/actionPlatform">actionPlatform</a>. It is not supposed to be comprehensive - when a suitable code is not enumerated here, textual or URL values can be used instead. These codes are at a fairly high level and do not deal with versioning and other nuance. Additional codes can be suggested <a href="https://github.com/schemaorg/schemaorg/issues/3057">in github</a>.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DigitalPlatformEnumeration extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/DigitalPlatformEnumeration";
}

