package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;

/**
 * Drug
 *
 * A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism. Here the term drug is used interchangeably with the term medicine although clinical knowledge make a clear difference between them.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Drug extends Substance {
  /**
   * An active ingredient, typically chemical compounds and/or biologic substances.
   */
  public String activeIngredient;

  /**
   * A route by which this drug may be administered, e.g. 'oral'.
   */
  public String administrationRoute;

  /**
   * Any precaution, guidance, contraindication, etc. related to consumption of alcohol while taking this drug.
   */
  public String alcoholWarning;

  /**
   * An available dosage strength for the drug.
   */
  public DrugStrength availableStrength;

  /**
   * Any precaution, guidance, contraindication, etc. related to this drug's use by breastfeeding mothers.
   */
  public String breastfeedingWarning;

  /**
   * Description of the absorption and elimination of drugs, including their concentration (pharmacokinetics, pK) and biological effects (pharmacodynamics, pD).
   */
  public String clinicalPharmacology;

  /**
   * A dosage form in which this drug/supplement is available, e.g. 'tablet', 'suspension', 'injection'.
   */
  public String dosageForm;

  /**
   * A dosing schedule for the drug for a given population, either observed, recommended, or maximum dose based on the type used.
   */
  public DoseSchedule doseSchedule;

  /**
   * The class of drug this belongs to (e.g., statins).
   */
  public DrugClass drugClass;

  /**
   * The unit in which the drug is measured, e.g. '5 mg tablet'.
   */
  public String drugUnit;

  /**
   * Any precaution, guidance, contraindication, etc. related to consumption of specific foods while taking this drug.
   */
  public String foodWarning;

  /**
   * The insurance plans that cover this drug.
   */
  public HealthInsurancePlan includedInHealthInsurancePlan;

  /**
   * Another drug that is known to interact with this drug in a way that impacts the effect of this drug or causes a risk to the patient. Note: disease interactions are typically captured as contraindications.
   */
  public Drug interactingDrug;

  /**
   * Link to the drug's label details.
   */
  public String labelDetails;

  /**
   * The drug or supplement's legal status, including any controlled substance schedules that apply.
   */
  public MedicalEnumeration legalStatusMedicalEnumeration;

  /**
   * The drug or supplement's legal status, including any controlled substance schedules that apply.
   */
  public DrugLegalStatus legalStatus;

  /**
   * The manufacturer of the product.
   */
  public Organization manufacturer;

  /**
   * Recommended intake of this supplement for a given population as defined by a specific recommending authority.
   */
  public MaximumDoseSchedule maximumIntake;

  /**
   * The specific biochemical interaction through which this drug or supplement produces its pharmacological effect.
   */
  public String mechanismOfAction;

  /**
   * The generic name of this drug or supplement.
   */
  public String nonProprietaryName;

  /**
   * Any information related to overdose on a drug, including signs or symptoms, treatments, contact information for emergency response.
   */
  public String overdosage;

  /**
   * Pregnancy category of this drug.
   */
  public DrugPregnancyCategory pregnancyCategory;

  /**
   * Any precaution, guidance, contraindication, etc. related to this drug's use during pregnancy.
   */
  public String pregnancyWarning;

  /**
   * Link to prescribing information for the drug.
   */
  public String prescribingInfo;

  /**
   * Indicates the status of drug prescription eg. local catalogs classifications or whether the drug is available by prescription or over-the-counter, etc.
   */
  public DrugPrescriptionStatus prescriptionStatus;

  /**
   * Proprietary name given to the diet plan, typically by its originator or creator.
   */
  public String proprietaryName;

  /**
   * Any other drug related to this one, for example commonly-prescribed alternatives.
   */
  public Drug relatedDrug;

  /**
   * The RxCUI drug identifier from RXNORM.
   */
  public String rxcui;

  /**
   * Any FDA or other warnings about the drug (text or URL).
   */
  public String warning;

  /**
   * True if the drug is available in a generic form (regardless of name).
   */
  public Boolean isAvailableGenerically;

  /**
   * True if this item's name is a proprietary/brand name (vs. generic name).
   */
  public Boolean isProprietary;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/Drug";
}

