package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * DrugStrength
 *
 * A specific strength in which a medical drug is available in a specific country.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class DrugStrength extends MedicalIntangible {
  /**
   * An active ingredient, typically chemical compounds and/or biologic substances.
   */
  public String activeIngredient;

  /**
   * The location in which the strength is available.
   */
  public AdministrativeArea availableIn;

  /**
   * Recommended intake of this supplement for a given population as defined by a specific recommending authority.
   */
  public MaximumDoseSchedule maximumIntake;

  /**
   * The units of an active ingredient's strength, e.g. mg.
   */
  public String strengthUnit;

  /**
   * The value of an active ingredient's strength, e.g. 325.
   */
  public BigDecimal strengthValue;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/DrugStrength";
}

