package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * EducationalOrganization
 *
 * An educational organization.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class EducationalOrganization extends CivicStructure {
  /**
   * Alumni of an organization.
   */
  public Person alumni;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/EducationalOrganization";

  public Organization organization;
}

