package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;

/**
 * HealthPlanFormulary
 *
 * For a given health insurance plan, the specification for costs and coverage of prescription drugs.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class HealthPlanFormulary extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/HealthPlanFormulary";

  /**
   * The tier(s) of drugs offered by this formulary or insurance plan.
   */
  public String healthPlanDrugTier;

  /**
   * Whether The costs to the patient for services under this network or formulary.
   */
  public Boolean healthPlanCostSharing;

  /**
   * Whether prescriptions can be delivered by mail.
   */
  public Boolean offersPrescriptionByMail;
}

