package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;

/**
 * HealthPlanNetwork
 *
 * A US-style health insurance plan network.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class HealthPlanNetwork extends Intangible {
  /**
   * Name or unique ID of network. (Networks are often reused across different insurance plans).
   */
  public String healthPlanNetworkId;

  /**
   * The tier(s) for this network.
   */
  public String healthPlanNetworkTier;

  /**
   * Whether The costs to the patient for services under this network or formulary.
   */
  public Boolean healthPlanCostSharing;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/HealthPlanNetwork";
}

