package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * HyperTocEntry
 *
 * A HyperToEntry is an item within a <a class="localLink" href="https://schema.org/HyperToc">HyperToc</a>, which represents a hypertext table of contents for complex media objects, such as <a class="localLink" href="https://schema.org/VideoObject">VideoObject</a>, <a class="localLink" href="https://schema.org/AudioObject">AudioObject</a>. The media object itself is indicated using <a class="localLink" href="https://schema.org/associatedMedia">associatedMedia</a>. Each section of interest within that content can be described with a <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a>, with associated <a class="localLink" href="https://schema.org/startOffset">startOffset</a> and <a class="localLink" href="https://schema.org/endOffset">endOffset</a>. When several entries are all from the same file, <a class="localLink" href="https://schema.org/associatedMedia">associatedMedia</a> is used on the overarching <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a>; if the content has been split into multiple files, they can be referenced using <a class="localLink" href="https://schema.org/associatedMedia">associatedMedia</a> on each <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a>.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class HyperTocEntry extends CreativeWork {
  /**
   * A media object that encodes this CreativeWork. This property is a synonym for encoding.
   */
  public MediaObject associatedMedia;

  /**
   * A <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a> can have a <a class="localLink" href="https://schema.org/tocContinuation">tocContinuation</a> indicated, which is another <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a> that would be the default next item to play or render.
   */
  public HyperTocEntry tocContinuation;

  /**
   * Text of an utterances (spoken words, lyrics etc.) that occurs at a certain section of a media object, represented as a <a class="localLink" href="https://schema.org/HyperTocEntry">HyperTocEntry</a>.
   */
  public String utterances;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/HyperTocEntry";
}

