package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;

/**
 * ImageObject
 *
 * An image file.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class ImageObject extends MediaObject {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/ImageObject";

  /**
   * The caption for this object. For downloadable machine formats (closed caption, subtitles etc.) use MediaObject and indicate the <a class="localLink" href="https://schema.org/encodingFormat">encodingFormat</a>.
   */
  public MediaObject caption;

  /**
   * Represents textual captioning from a <a class="localLink" href="https://schema.org/MediaObject">MediaObject</a>, e.g. text of a 'meme'.
   */
  public String embeddedTextCaption;

  /**
   * exif data for this object.
   */
  public PropertyValue exifData;

  /**
   * Thumbnail image for an image or video.
   */
  public ImageObject thumbnail;

  /**
   * Indicates whether this image is representative of the content of the page.
   */
  public Boolean representativeOfPage;
}

