package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigInteger;
import java.time.ZonedDateTime;

/**
 * InteractionCounter
 *
 * A summary of how users have interacted with this CreativeWork. In most cases, authors will use a subtype to specify the specific type of interaction.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class InteractionCounter extends StructuredValue {
  /**
   * The WebSite or SoftwareApplication where the interactions took place.
   */
  public WebSite interactionServiceWebSite;

  /**
   * The WebSite or SoftwareApplication where the interactions took place.
   */
  public SoftwareApplication interactionService;

  /**
   * The Action representing the type of interaction. For up votes, +1s, etc. use <a class="localLink" href="https://schema.org/LikeAction">LikeAction</a>. For down votes use <a class="localLink" href="https://schema.org/DislikeAction">DislikeAction</a>. Otherwise, use the most specific Action.
   */
  public Action interactionType;

  /**
   * The location of, for example, where an event is happening, where an organization is located, or where an action takes place.
   */
  public Place locationPlace;

  /**
   * The location of, for example, where an event is happening, where an organization is located, or where an action takes place.
   */
  public VirtualLocation locationVirtualLocation;

  /**
   * The location of, for example, where an event is happening, where an organization is located, or where an action takes place.
   */
  public PostalAddress location;

  /**
   * The endTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to end. For actions that span a period of time, when the action was performed. e.g. John wrote a book from January to <em>December</em>. For media, including audio and video, it's the time offset of the end of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime endTimeZonedDateTime;

  /**
   * The endTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to end. For actions that span a period of time, when the action was performed. e.g. John wrote a book from January to <em>December</em>. For media, including audio and video, it's the time offset of the end of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime endTime;

  /**
   * The startTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to start. For actions that span a period of time, when the action was performed. e.g. John wrote a book from <em>January</em> to December. For media, including audio and video, it's the time offset of the start of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime startTimeZonedDateTime;

  /**
   * The startTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to start. For actions that span a period of time, when the action was performed. e.g. John wrote a book from <em>January</em> to December. For media, including audio and video, it's the time offset of the start of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime startTime;

  /**
   * The number of interactions for the CreativeWork using the WebSite or SoftwareApplication.
   */
  public BigInteger userInteractionCount;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/InteractionCounter";
}

