package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;
import java.math.BigDecimal;

/**
 * LoanOrCredit
 *
 * A financial product for the loaning of an amount of money, or line of credit, under agreed terms and charges.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class LoanOrCredit extends FinancialProduct {
  /**
   * The amount of money.
   */
  public MonetaryAmount amountMonetaryAmount;

  /**
   * The amount of money.
   */
  public BigDecimal amount;

  /**
   * The currency in which the monetary amount is expressed.<br/><br/>
   *
   * Use standard formats: <a href="http://en.wikipedia.org/wiki/ISO_4217">ISO 4217 currency format</a> e.g. "USD"; <a href="https://en.wikipedia.org/wiki/List_of_cryptocurrencies">Ticker symbol</a> for cryptocurrencies e.g. "BTC"; well known names for <a href="https://en.wikipedia.org/wiki/Local_exchange_trading_system">Local Exchange Tradings Systems</a> (LETS) and other currency types e.g. "Ithaca HOUR".
   */
  public String currency;

  /**
   * The period of time after any due date that the borrower has to fulfil its obligations before a default (failure to pay) is deemed to have occurred.
   */
  public Duration gracePeriod;

  /**
   * A form of paying back money previously borrowed from a lender. Repayment usually takes the form of periodic payments that normally include part principal plus interest in each payment.
   */
  public RepaymentSpecification loanRepaymentForm;

  /**
   * The duration of the loan or credit agreement.
   */
  public QuantitativeValue loanTerm;

  /**
   * The type of a loan or credit.
   */
  public String loanType;

  /**
   * Assets required to secure loan or credit repayments. It may take form of third party pledge, goods, financial instruments (cash, securities, etc.)
   */
  public Thing requiredCollateral;

  /**
   * The only way you get the money back in the event of default is the security. Recourse is where you still have the opportunity to go back to the borrower for the rest of the money.
   */
  public Boolean recourseLoan;

  /**
   * Whether the terms for payment of interest can be renegotiated during the life of the loan.
   */
  public Boolean renegotiableLoan;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/LoanOrCredit";
}

