package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * Map
 *
 * A map.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Map extends CreativeWork {
  /**
   * Indicates the kind of Map, from the MapCategoryType Enumeration.
   */
  public MapCategoryType mapType;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Map";
}

