package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MedicalSignOrSymptom
 *
 * Any feature associated or not with a medical condition. In medicine a symptom is generally subjective while a sign is objective.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalSignOrSymptom extends MedicalCondition {
  /**
   * A possible treatment to address this condition, sign or symptom.
   */
  public MedicalTherapy possibleTreatment;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalSignOrSymptom";
}

