package uk.co.polycode.ontology.lib.org.schema;

import java.lang.Boolean;
import java.lang.String;
import java.net.URL;
import java.time.ZonedDateTime;

/**
 * MediaObject
 *
 * A media object, such as an image, video, or audio object embedded in a web page or a downloadable dataset i.e. DataDownload. Note that a creative work may have many media objects associated with it on the same web page. For example, a page about a single song (MusicRecording) may have a music video (VideoObject), and a high and low bandwidth audio stream (2 AudioObject's).
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MediaObject extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/MediaObject";

  /**
   * A NewsArticle associated with the Media Object.
   */
  public NewsArticle associatedArticle;

  /**
   * The bitrate of the media object.
   */
  public String bitrate;

  /**
   * File size in (mega/kilo) bytes.
   */
  public String contentSize;

  /**
   * Actual bytes of the media object, for example the image file or video file.
   */
  public URL contentUrl;

  /**
   * The duration of the item (movie, audio recording, event, etc.) in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>.
   */
  public Duration duration;

  /**
   * A URL pointing to a player for a specific video. In general, this is the information in the <code>src</code> element of an <code>embed</code> tag and should not be the same as the content of the <code>loc</code> tag.
   */
  public URL embedUrl;

  /**
   * The CreativeWork encoded by this media object.
   */
  public CreativeWork encodesCreativeWork;

  /**
   * Media type typically expressed using a MIME format (see <a href="http://www.iana.org/assignments/media-types/media-types.xhtml">IANA site</a> and <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types">MDN reference</a>) e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.).<br/><br/>
   *
   * In cases where a <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a> has several media type representations, <a class="localLink" href="https://schema.org/encoding">encoding</a> can be used to indicate each <a class="localLink" href="https://schema.org/MediaObject">MediaObject</a> alongside particular <a class="localLink" href="https://schema.org/encodingFormat">encodingFormat</a> information.<br/><br/>
   *
   * Unregistered or niche encoding and file formats can be indicated instead via the most appropriate URL, e.g. defining Web page or a Wikipedia/Wikidata entry.
   */
  public String encodingFormat;

  /**
   * The height of the item.
   */
  public Distance height;

  /**
   * The height of the item.
   */
  public QuantitativeValue heightQuantitativeValue;

  /**
   * The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is not valid, e.g. a region where the transaction is not allowed.<br/><br/>
   *
   * See also <a class="localLink" href="https://schema.org/eligibleRegion">eligibleRegion</a>.
   */
  public Place ineligibleRegion;

  /**
   * The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is not valid, e.g. a region where the transaction is not allowed.<br/><br/>
   *
   * See also <a class="localLink" href="https://schema.org/eligibleRegion">eligibleRegion</a>.
   */
  public GeoShape ineligibleRegionGeoShape;

  /**
   * Used to indicate a specific claim contained, implied, translated or refined from the content of a <a class="localLink" href="https://schema.org/MediaObject">MediaObject</a> or other <a class="localLink" href="https://schema.org/CreativeWork">CreativeWork</a>. The interpreting party can be indicated using <a class="localLink" href="https://schema.org/claimInterpreter">claimInterpreter</a>.
   */
  public Claim interpretedAsClaim;

  /**
   * Player type required&#x2014;for example, Flash or Silverlight.
   */
  public String playerType;

  /**
   * The production company or studio responsible for the item e.g. series, video game, episode etc.
   */
  public Organization productionCompany;

  /**
   * The regions where the media is allowed. If not specified, then it's assumed to be allowed everywhere. Specify the countries in <a href="http://en.wikipedia.org/wiki/ISO_3166">ISO 3166 format</a>.
   */
  public Place regionsAllowed;

  /**
   * Indicates if use of the media require a subscription  (either paid or free). Allowed values are <code>true</code> or <code>false</code> (note that an earlier version had 'yes', 'no').
   */
  public MediaSubscription requiresSubscription;

  /**
   * Indicates if use of the media require a subscription  (either paid or free). Allowed values are <code>true</code> or <code>false</code> (note that an earlier version had 'yes', 'no').
   */
  public Boolean requiresSubscriptionBoolean;

  /**
   * The <a href="https://en.wikipedia.org/wiki/SHA-2">SHA-2</a> SHA256 hash of the content of the item. For example, a zero-length input has value 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
   */
  public String sha256;

  /**
   * The width of the item.
   */
  public QuantitativeValue width;

  /**
   * The width of the item.
   */
  public Distance widthDistance;

  /**
   * The endTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to end. For actions that span a period of time, when the action was performed. e.g. John wrote a book from January to <em>December</em>. For media, including audio and video, it's the time offset of the end of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime endTime;

  /**
   * The endTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to end. For actions that span a period of time, when the action was performed. e.g. John wrote a book from January to <em>December</em>. For media, including audio and video, it's the time offset of the end of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime endTimeZonedDateTime;

  /**
   * The startTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to start. For actions that span a period of time, when the action was performed. e.g. John wrote a book from <em>January</em> to December. For media, including audio and video, it's the time offset of the start of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime startTime;

  /**
   * The startTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to start. For actions that span a period of time, when the action was performed. e.g. John wrote a book from <em>January</em> to December. For media, including audio and video, it's the time offset of the start of a clip within a larger file.<br/><br/>
   *
   * Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.
   */
  public ZonedDateTime startTimeZonedDateTime;

  /**
   * Date when this media object was uploaded to this site.
   */
  public ZonedDateTime uploadDate;
}

