package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MedicalSign
 *
 * Any physical manifestation of a person's medical condition discoverable by objective diagnostic tests or physical examination.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalSign extends MedicalSignOrSymptom {
  /**
   * A physical examination that can identify this sign.
   */
  public PhysicalExam identifyingExam;

  /**
   * A diagnostic test that can identify this sign.
   */
  public MedicalTest identifyingTest;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalSign";
}

