package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MedicalTest
 *
 * Any medical test, typically performed for diagnostic purposes.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalTest extends MedicalEntity {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalTest";

  /**
   * Drugs that affect the test's results.
   */
  public Drug affectedBy;

  /**
   * Range of acceptable values for a typical patient, when applicable.
   */
  public MedicalEnumeration normalRange;

  /**
   * A sign detected by the test.
   */
  public MedicalSign signDetected;

  /**
   * A condition the test is used to diagnose.
   */
  public MedicalCondition usedToDiagnose;

  /**
   * Device used to perform the test.
   */
  public MedicalDevice usesDevice;
}

