package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MedicalCondition
 *
 * Any condition of the human body that affects the normal functioning of a person, whether physically or mentally. Includes diseases, injuries, disabilities, disorders, syndromes, etc.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalCondition extends MedicalEntity {
  /**
   * The anatomy of the underlying organ system or structures associated with this entity.
   */
  public AnatomicalSystem associatedAnatomyAnatomicalSystem;

  /**
   * The anatomy of the underlying organ system or structures associated with this entity.
   */
  public AnatomicalStructure associatedAnatomyAnatomicalStructure;

  /**
   * The anatomy of the underlying organ system or structures associated with this entity.
   */
  public SuperficialAnatomy associatedAnatomy;

  /**
   * One of a set of differential diagnoses for the condition. Specifically, a closely-related or competing diagnosis typically considered later in the cognitive process whereby this medical condition is distinguished from others most likely responsible for a similar collection of signs and symptoms to reach the most parsimonious diagnosis or diagnoses in a patient.
   */
  public DDxElement differentialDiagnosis;

  /**
   * Specifying a drug or medicine used in a medication procedure.
   */
  public Drug drug;

  /**
   * The characteristics of associated patients, such as age, gender, race etc.
   */
  public String epidemiology;

  /**
   * The likely outcome in either the short term or long term of the medical condition.
   */
  public String expectedPrognosis;

  /**
   * The expected progression of the condition if it is not treated and allowed to progress naturally.
   */
  public String naturalProgression;

  /**
   * Changes in the normal mechanical, physical, and biochemical functions that are associated with this activity or condition.
   */
  public String pathophysiology;

  /**
   * A possible unexpected and unfavorable evolution of a medical condition. Complications may include worsening of the signs or symptoms of the disease, extension of the condition to other organ systems, etc.
   */
  public String possibleComplication;

  /**
   * A possible treatment to address this condition, sign or symptom.
   */
  public MedicalTherapy possibleTreatment;

  /**
   * A preventative therapy used to prevent an initial occurrence of the medical condition, such as vaccination.
   */
  public MedicalTherapy primaryPrevention;

  /**
   * A modifiable or non-modifiable factor that increases the risk of a patient contracting this condition, e.g. age,  coexisting condition.
   */
  public MedicalRiskFactor riskFactor;

  /**
   * A preventative therapy used to prevent reoccurrence of the medical condition after an initial episode of the condition.
   */
  public MedicalTherapy secondaryPrevention;

  /**
   * A sign or symptom of this condition. Signs are objective or physically observable manifestations of the medical condition while symptoms are the subjective experience of the medical condition.
   */
  public MedicalSignOrSymptom signOrSymptom;

  /**
   * The stage of the condition, if applicable.
   */
  public MedicalConditionStage stage;

  /**
   * The status of the study (enumerated).
   */
  public EventStatusType statusEventStatusType;

  /**
   * The status of the study (enumerated).
   */
  public MedicalStudyStatus status;

  /**
   * A medical test typically performed given this condition.
   */
  public MedicalTest typicalTest;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalCondition";
}

