package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MedicalEntity
 *
 * The most generic type of entity related to health and the practice of medicine.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MedicalEntity extends Thing {
  /**
   * A medical code for the entity, taken from a controlled vocabulary or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
   */
  public MedicalCode code;

  /**
   * A <a class="localLink" href="https://schema.org/Grant">Grant</a> that directly or indirectly provide funding or sponsorship for this item. See also <a class="localLink" href="https://schema.org/ownershipFundingInfo">ownershipFundingInfo</a>.
   */
  public Grant funding;

  /**
   * A medical guideline related to this entity.
   */
  public MedicalGuideline guideline;

  /**
   * The drug or supplement's legal status, including any controlled substance schedules that apply.
   */
  public MedicalEnumeration legalStatusMedicalEnumeration;

  /**
   * The drug or supplement's legal status, including any controlled substance schedules that apply.
   */
  public DrugLegalStatus legalStatus;

  /**
   * The system of medicine that includes this MedicalEntity, for example 'evidence-based', 'homeopathic', 'chiropractic', etc.
   */
  public MedicineSystem medicineSystem;

  /**
   * If applicable, the organization that officially recognizes this entity as part of its endorsed system of medicine.
   */
  public Organization recognizingAuthority;

  /**
   * If applicable, a medical specialty in which this entity is relevant.
   */
  public MedicalSpecialty relevantSpecialty;

  /**
   * A medical study or trial related to this entity.
   */
  public MedicalStudy study;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/MedicalEntity";
}

