package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigInteger;
import java.time.ZonedDateTime;

/**
 * MerchantReturnPolicySeasonalOverride
 *
 * A seasonal override of a return policy, for example used for holidays.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MerchantReturnPolicySeasonalOverride extends Intangible {
  /**
   * Specifies an applicable return policy (from an enumeration).
   */
  public MerchantReturnEnumeration returnPolicyCategory;

  /**
   * The end date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime endDateZonedDateTime;

  /**
   * The end date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime endDate;

  /**
   * Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the <a class="localLink" href="https://schema.org/returnPolicyCategory">returnPolicyCategory</a> property is specified as <a class="localLink" href="https://schema.org/MerchantReturnFiniteReturnWindow">MerchantReturnFiniteReturnWindow</a>.
   */
  public ZonedDateTime merchantReturnDaysZonedDateTime;

  /**
   * Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the <a class="localLink" href="https://schema.org/returnPolicyCategory">returnPolicyCategory</a> property is specified as <a class="localLink" href="https://schema.org/MerchantReturnFiniteReturnWindow">MerchantReturnFiniteReturnWindow</a>.
   */
  public BigInteger merchantReturnDaysBigInteger;

  /**
   * Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the <a class="localLink" href="https://schema.org/returnPolicyCategory">returnPolicyCategory</a> property is specified as <a class="localLink" href="https://schema.org/MerchantReturnFiniteReturnWindow">MerchantReturnFiniteReturnWindow</a>.
   */
  public ZonedDateTime merchantReturnDays;

  /**
   * The start date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime startDateZonedDateTime;

  /**
   * The start date and time of the item (in <a href="http://en.wikipedia.org/wiki/ISO_8601">ISO 8601 date format</a>).
   */
  public ZonedDateTime startDate;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/MerchantReturnPolicySeasonalOverride";
}

