package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * MusicComposition
 *
 * A musical composition.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class MusicComposition extends CreativeWork {
  /**
   * The person or organization who wrote a composition, or who is the composer of a work performed at some event.
   */
  public Organization composerOrganization;

  /**
   * The person or organization who wrote a composition, or who is the composer of a work performed at some event.
   */
  public Person composer;

  /**
   * The date and place the work was first performed.
   */
  public Event firstPerformance;

  /**
   * Smaller compositions included in this work (e.g. a movement in a symphony).
   */
  public MusicComposition includedComposition;

  /**
   * The International Standard Musical Work Code for the composition.
   */
  public String iswcCode;

  /**
   * The person who wrote the words.
   */
  public Person lyricist;

  /**
   * The words in the song.
   */
  public CreativeWork lyrics;

  /**
   * An arrangement derived from the composition.
   */
  public MusicComposition musicArrangement;

  /**
   * The type of composition (e.g. overture, sonata, symphony, etc.).
   */
  public String musicCompositionForm;

  /**
   * The key, mode, or scale this composition uses.
   */
  public String musicalKey;

  /**
   * An audio recording of the work.
   */
  public MusicRecording recordedAs;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/MusicComposition";
}

