package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.math.BigDecimal;

/**
 * Occupation
 *
 * A profession, may involve prolonged training and/or a formal qualification.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Occupation extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Occupation";

  /**
   * Educational background needed for the position or Occupation.
   */
  public EducationalOccupationalCredential educationRequirements;

  /**
   * An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.
   */
  public MonetaryAmountDistribution estimatedSalary;

  /**
   * An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.
   */
  public MonetaryAmount estimatedSalaryMonetaryAmount;

  /**
   * An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.
   */
  public BigDecimal estimatedSalaryBigDecimal;

  /**
   * Description of skills and experience needed for the position or Occupation.
   */
  public OccupationalExperienceRequirements experienceRequirements;

  /**
   * The region/country for which this occupational description is appropriate. Note that educational requirements and qualifications can vary between jurisdictions.
   */
  public AdministrativeArea occupationLocation;

  /**
   * A category describing the job, preferably using a term from a taxonomy such as <a href="http://www.onetcenter.org/taxonomy.html">BLS O*NET-SOC</a>, <a href="https://www.ilo.org/public/english/bureau/stat/isco/isco08/">ISCO-08</a> or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.<br/><br/>
   *
   * Note: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.
   */
  public CategoryCode occupationalCategory;

  /**
   * Specific qualifications required for this role or Occupation.
   */
  public EducationalOccupationalCredential qualifications;

  /**
   * Responsibilities associated with this role or Occupation.
   */
  public String responsibilities;

  /**
   * A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is desired or required to fulfill this role or to work in this occupation.
   */
  public DefinedTerm skills;
}

