package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * PhysicalExam
 *
 * A type of physical examination of a patient performed by a physician.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class PhysicalExam extends MedicalEnumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://health-lifesci.schema.org/PhysicalExam";

  public MedicalProcedure medicalProcedure;
}

