package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * Review
 *
 * A review of an item - for example, of a restaurant, movie, or store.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class Review extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/Review";

  /**
   * An associated <a class="localLink" href="https://schema.org/ClaimReview">ClaimReview</a>, related by specific common content, topic or claim. The expectation is that this property would be most typically used in cases where a single activity is conducting both claim reviews and media reviews, in which case <a class="localLink" href="https://schema.org/relatedMediaReview">relatedMediaReview</a> would commonly be used on a <a class="localLink" href="https://schema.org/ClaimReview">ClaimReview</a>, while <a class="localLink" href="https://schema.org/relatedClaimReview">relatedClaimReview</a> would be used on <a class="localLink" href="https://schema.org/MediaReview">MediaReview</a>.
   */
  public Review associatedClaimReview;

  /**
   * An associated <a class="localLink" href="https://schema.org/MediaReview">MediaReview</a>, related by specific common content, topic or claim. The expectation is that this property would be most typically used in cases where a single activity is conducting both claim reviews and media reviews, in which case <a class="localLink" href="https://schema.org/relatedMediaReview">relatedMediaReview</a> would commonly be used on a <a class="localLink" href="https://schema.org/ClaimReview">ClaimReview</a>, while <a class="localLink" href="https://schema.org/relatedClaimReview">relatedClaimReview</a> would be used on <a class="localLink" href="https://schema.org/MediaReview">MediaReview</a>.
   */
  public Review associatedMediaReview;

  /**
   * An associated <a class="localLink" href="https://schema.org/Review">Review</a>.
   */
  public Review associatedReview;

  /**
   * The item that is being reviewed/rated.
   */
  public Thing itemReviewed;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), negative considerations - either as unstructured text, or a list.
   */
  public ItemList negativeNotes;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), negative considerations - either as unstructured text, or a list.
   */
  public ListItem negativeNotesListItem;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), negative considerations - either as unstructured text, or a list.
   */
  public WebContent negativeNotesWebContent;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), positive considerations - either as unstructured text, or a list.
   */
  public ItemList positiveNotes;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), positive considerations - either as unstructured text, or a list.
   */
  public ListItem positiveNotesListItem;

  /**
   * Indicates, in the context of a <a class="localLink" href="https://schema.org/Review">Review</a> (e.g. framed as 'pro' vs 'con' considerations), positive considerations - either as unstructured text, or a list.
   */
  public WebContent positiveNotesWebContent;

  /**
   * This Review or Rating is relevant to this part or facet of the itemReviewed.
   */
  public String reviewAspect;

  /**
   * The actual body of the review.
   */
  public String reviewBody;

  /**
   * The rating given in this review. Note that reviews can themselves be rated. The <code>reviewRating</code> applies to rating given by the review. The <a class="localLink" href="https://schema.org/aggregateRating">aggregateRating</a> property applies to the review itself, as a creative work.
   */
  public Rating reviewRating;
}

