package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.net.URL;

/**
 * ServiceChannel
 *
 * A means for accessing a service, e.g. a government office location, web site, or phone number.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class ServiceChannel extends Intangible {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/ServiceChannel";

  /**
   * A language someone may use with or at the item, service or place. Please use one of the language codes from the <a href="http://tools.ietf.org/html/bcp47">IETF BCP 47 standard</a>. See also <a class="localLink" href="https://schema.org/inLanguage">inLanguage</a>
   */
  public Language availableLanguage;

  /**
   * Estimated processing time for the service using this channel.
   */
  public Duration processingTime;

  /**
   * The service provided by this channel.
   */
  public Service providesService;

  /**
   * The location (e.g. civic structure, local business, etc.) where a person can go to access the service.
   */
  public Place serviceLocation;

  /**
   * The phone number to use to access the service.
   */
  public ContactPoint servicePhone;

  /**
   * The address for accessing the service by mail.
   */
  public PostalAddress servicePostalAddress;

  /**
   * The number to access the service by text message.
   */
  public ContactPoint serviceSmsNumber;

  /**
   * The website to access the service.
   */
  public URL serviceUrl;
}

