package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * SizeSpecification
 *
 * Size related properties of a product, typically a size code (<a class="localLink" href="https://schema.org/name">name</a>) and optionally a <a class="localLink" href="https://schema.org/sizeSystem">sizeSystem</a>, <a class="localLink" href="https://schema.org/sizeGroup">sizeGroup</a>, and product measurements (<a class="localLink" href="https://schema.org/hasMeasurement">hasMeasurement</a>). In addition, the intended audience can be defined through <a class="localLink" href="https://schema.org/suggestedAge">suggestedAge</a>, <a class="localLink" href="https://schema.org/suggestedGender">suggestedGender</a>, and suggested body measurements (<a class="localLink" href="https://schema.org/suggestedMeasurement">suggestedMeasurement</a>).
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class SizeSpecification extends QualitativeValue {
  /**
   * A product measurement, for example the inseam of pants, the wheel size of a bicycle, or the gauge of a screw. Usually an exact measurement, but can also be a range of measurements for adjustable products, for example belts and ski bindings.
   */
  public QuantitativeValue hasMeasurement;

  /**
   * The size group (also known as "size type") for a product's size. Size groups are common in the fashion industry to define size segments and suggested audiences for wearable products. Multiple values can be combined, for example "men's big and tall", "petite maternity" or "regular"
   */
  public SizeGroupEnumeration sizeGroup;

  /**
   * The size system used to identify a product's size. Typically either a standard (for example, "GS1" or "ISO-EN13402"), country code (for example "US" or "JP"), or a measuring system (for example "Metric" or "Imperial").
   */
  public SizeSystemEnumeration sizeSystem;

  /**
   * The age or age range for the intended audience or person, for example 3-12 months for infants, 1-5 years for toddlers.
   */
  public QuantitativeValue suggestedAge;

  /**
   * The suggested gender of the intended person or audience, for example "male", "female", or "unisex".
   */
  public GenderType suggestedGender;

  /**
   * A suggested range of body measurements for the intended audience or person, for example inseam between 32 and 34 inches or height between 170 and 190 cm. Typically found on a size chart for wearable products.
   */
  public QuantitativeValue suggestedMeasurement;

  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://pending.schema.org/SizeSpecification";
}

