package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;
import java.net.URL;

/**
 * SoftwareApplication
 *
 * A software application.
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class SoftwareApplication extends CreativeWork {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/SoftwareApplication";

  /**
   * Type of software application, e.g. 'Game, Multimedia'.
   */
  public String applicationCategory;

  /**
   * Subcategory of the application, e.g. 'Arcade Game'.
   */
  public String applicationSubCategory;

  /**
   * The name of the application suite to which the application belongs (e.g. Excel belongs to Office).
   */
  public String applicationSuite;

  /**
   * Device required to run the application. Used in cases where a specific make/model is required to run the application.
   */
  public String availableOnDevice;

  /**
   * Countries for which the application is not supported. You can also provide the two-letter ISO 3166-1 alpha-2 country code.
   */
  public String countriesNotSupported;

  /**
   * Countries for which the application is supported. You can also provide the two-letter ISO 3166-1 alpha-2 country code.
   */
  public String countriesSupported;

  /**
   * If the file can be downloaded, URL to download the binary.
   */
  public URL downloadUrl;

  /**
   * Features or modules provided by this application (and possibly required by other applications).
   */
  public String featureList;

  /**
   * Size of the application / package (e.g. 18MB). In the absence of a unit (MB, KB etc.), KB will be assumed.
   */
  public String fileSize;

  /**
   * URL at which the app may be installed, if different from the URL of the item.
   */
  public URL installUrl;

  /**
   * Minimum memory requirements.
   */
  public String memoryRequirements;

  /**
   * Operating systems supported (Windows 7, OSX 10.6, Android 1.6).
   */
  public String operatingSystem;

  /**
   * Permission(s) required to run the app (for example, a mobile app may require full internet access or may run only on wifi).
   */
  public String permissions;

  /**
   * Processor architecture required to run the application (e.g. IA64).
   */
  public String processorRequirements;

  /**
   * Description of what changed in this version.
   */
  public String releaseNotes;

  /**
   * A link to a screenshot image of the app.
   */
  public ImageObject screenshot;

  /**
   * Additional content for a software application.
   */
  public SoftwareApplication softwareAddOn;

  /**
   * Software application help.
   */
  public CreativeWork softwareHelp;

  /**
   * Component dependency requirements for application. This includes runtime environments and shared libraries that are not included in the application distribution package, but required to run the application (Examples: DirectX, Java or .NET runtime).
   */
  public String softwareRequirements;

  /**
   * Version of the software instance.
   */
  public String softwareVersion;

  /**
   * Storage requirements (free space required).
   */
  public String storageRequirements;

  /**
   * Supporting data for a SoftwareApplication.
   */
  public DataFeed supportingData;
}

