package uk.co.polycode.ontology.lib.org.schema;

import java.lang.String;

/**
 * WarrantyScope
 *
 * A range of of services that will be provided to a customer free of charge in case of a defect or malfunction of a product.<br/><br/>
 *
 * Commonly used values:<br/><br/>
 *
 * <ul>
 * <li>http://purl.org/goodrelations/v1#Labor-BringIn</li>
 * <li>http://purl.org/goodrelations/v1#PartsAndLabor-BringIn</li>
 * <li>http://purl.org/goodrelations/v1#PartsAndLabor-PickUp</li>
 * </ul>
 *
 *
 *
 *             This file was generated by OWL to Java as a transformation of the Schema.org schema Version 14.0.
 *             Schema.org is released under the Creative Commons Attribution-ShareAlike License (version 3.0). 
 *             The Schema.org license is applicable to the generated source files and the license is available from 
 *             https://creativecommons.org/licenses/by-sa/3.0/
 *             
 */
public class WarrantyScope extends Enumeration {
  /**
   * Where to find the definition of the OWL Class used to generate this Java class.
   */
  public String isDefinedBy = "https://schema.org/WarrantyScope";
}

